AutoMQ/automq

- clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java
- clients/src/main/java/org/apache/kafka/common/requests/RequestContext.java
- core/src/main/scala/kafka/network/RequestChannel.scala
- core/src/main/scala/kafka/network/SocketServer.scala
- core/src/main/scala/kafka/server/EnvelopeUtils.scala
- core/src/main/scala/kafka/server/KafkaApis.scala
- core/src/main/scala/kafka/server/KafkaRequestHandler.scala
close https://github.com/AutoMQ/automq-for-kafka/issues/433
> feat(issues433-network): pipeline the connection requests

- core/src/main/scala/kafka/server/ReplicaManager.scala
https://github.com/AutoMQ/automq-for-kafka/issues/460
> fix(issues460): guard read thread unsafe array

- checkstyle/import-control-core.xml
- core/src/main/scala/kafka/log/stream/s3/failover/FailoverListener.java
- gradle/dependencies.gradle
- metadata/src/main/java/org/apache/kafka/controller/stream/FailoverControlManager.java
https://github.com/AutoMQ/automq-for-kafka/issues/447%20/opt/automq/scripts/amq-serverless
> feat(issues447): integrate serverless

- core/src/main/scala/kafka/log/streamaspect/AlwaysSuccessClient.java
- core/src/main/scala/kafka/log/streamaspect/DefaultElasticStreamSlice.java
- core/src/main/scala/kafka/log/streamaspect/ElasticLogFileRecords.java
- core/src/main/scala/kafka/log/streamaspect/ElasticStreamSlice.java
- core/src/main/scala/kafka/log/streamaspect/LazyStream.java
- core/src/main/scala/kafka/log/streamaspect/MemoryClient.java
- core/src/main/scala/kafka/log/streamaspect/MetaStream.java
- core/src/main/scala/kafka/log/streamaspect/ReadHint.java
- core/src/main/scala/kafka/server/DelayedFetch.scala
- core/src/main/scala/kafka/server/KafkaApis.scala
- core/src/main/scala/kafka/server/ReplicaManager.scala
- core/src/test/java/kafka/log/streamaspect/AlwaysSuccessClientTest.java
- gradle/dependencies.gradle
close https://github.com/AutoMQ/automq-for-kafka/issues/471
> feat(issues471): isolate fast / slow read

- gradle/dependencies.gradle
- metadata/src/main/java/org/apache/kafka/controller/stream/FailoverControlManager.java
- fix(kafka_issues475): do not log when fast fail
> feat(s3stream): update to 0.6.3

- gradle/dependencies.gradle
- metadata/src/main/java/org/apache/kafka/controller/stream/FailoverControlManager.java
close https://github.com/AutoMQ/automq-for-kafka/issues/447
> feat(issues447): add more failover log and update s3stream to 0.6.4

- build.gradle
- gradle/dependencies.gradle
close https://github.com/AutoMQ/automq-for-kafka/issues/213
> feat: add boring ssl

- core/src/main/scala/kafka/cluster/Partition.scala
- core/src/main/scala/kafka/log/stream/s3/DefaultS3Client.java
- core/src/main/scala/kafka/log/stream/s3/network/ControllerRequestSender.java
- core/src/main/scala/kafka/log/stream/s3/streams/ControllerStreamManager.java
- core/src/main/scala/kafka/log/streamaspect/AlwaysSuccessClient.java
- core/src/main/scala/kafka/log/streamaspect/ElasticLogFileRecords.java
- core/src/main/scala/kafka/log/streamaspect/ElasticLogSegment.scala
- core/src/main/scala/kafka/log/streamaspect/ElasticStreamSegmentMeta.java
- core/src/main/scala/kafka/server/BrokerServer.scala
- core/src/main/scala/kafka/server/ReplicaManager.scala
- core/src/test/java/kafka/log/stream/s3/ControllerRequestSenderTest.java
- gradle/dependencies.gradle
- tests/kafkatest/services/kafka/kafka.py
- tests/kafkatest/services/kafka/templates/log4j.properties
close https://github.com/AutoMQ/automq-for-kafka/issues/505
> fix(issues505): get first batch timestamp from meta

- core/src/main/scala/kafka/server/ReplicaManager.scala
close https://github.com/AutoMQ/automq-for-kafka/issues/532
> feat(issues532): optimize the impact of Partition migration on traffic

- core/src/main/scala/kafka/server/BrokerServer.scala
- core/src/main/scala/kafka/server/ReplicaManager.scala
https://github.com/AutoMQ/automq-for-kafka/issues/540
> fix(issues540): await all partitions close before metadata listener shutdown

- core/src/main/scala/kafka/log/streamaspect/ElasticLogFileRecords.java
- core/src/main/scala/kafka/server/ReplicaManager.scala
https://github.com/AutoMQ/automq-for-kafka/issues/543
> feat(issues543): use pooled bytebuf for PooledMemoryRecords

- core/src/main/scala/kafka/log/streamaspect/ElasticLogFileRecords.java
close https://github.com/AutoMQ/automq-for-kafka/issues/550
close https://github.com/AutoMQ/automq-for-kafka/issues/549
> fix(issuses550): PooledMemoryRecords memory leak

- core/src/test/java/kafka/log/stream/s3/StreamMetadataManagerTest.java
- metadata/src/main/java/org/apache/kafka/image/DeltaMap.java
- metadata/src/main/java/org/apache/kafka/image/S3ObjectsDelta.java
- metadata/src/main/java/org/apache/kafka/image/S3ObjectsImage.java
- metadata/src/test/java/org/apache/kafka/image/DeltaMapTest.java
- metadata/src/test/java/org/apache/kafka/image/S3ObjectsImageTest.java
close https://github.com/AutoMQ/automq-for-kafka/issues/542
> feat(issues542): optimize S3ObjectsDelta memory usage

- gradle/dependencies.gradle
close https://github.com/AutoMQ/automq-for-kafka/issues/581
> feat: bump s3stream to 0.8.0

- core/src/main/scala/kafka/server/ReplicaManager.scala
> perf(ReplicaManager): speed up shutdown

- core/src/main/scala/kafka/log/stream/s3/network/ControllerRequestSender.java
- metadata/src/main/java/org/apache/kafka/controller/stream/StreamControlManager.java
- tests/kafkatest/tests/end_to_end.py
close https://github.com/AutoMQ/automq-for-kafka/issues/598
> fix(issues598): fix test_replication_with_broker_failure fail

- core/src/main/scala/kafka/server/DelayedFetch.scala
- core/src/main/scala/kafka/server/FairLimiter.java
- core/src/main/scala/kafka/server/Limiter.java
- core/src/main/scala/kafka/server/MemoryLimiter.java
- core/src/main/scala/kafka/server/NoopLimiter.java
- core/src/main/scala/kafka/server/ReplicaManager.scala
> perf(server): speed up delayed fetch

- NOTICE
- NOTICE-binary
> chore: polish the NOTICE files

- core/src/main/scala/kafka/cluster/Partition.scala
Reverts AutoMQ/automq-for-kafka#651
> revert: perf: return fast when the `fetchOffset` equals to the `confirmOffset`

- core/src/main/scala/kafka/log/CachedLogSegments.scala
- core/src/main/scala/kafka/log/UnifiedLog.scala
- core/src/main/scala/kafka/log/streamaspect/ElasticLog.scala
> perf: check the last segment first to avoid calling `floorSegment`

- core/src/main/scala/kafka/cluster/Partition.scala
- core/src/main/scala/kafka/log/CachedLogSegments.scala
- core/src/main/scala/kafka/log/streamaspect/DefaultElasticStreamSlice.java
- core/src/main/scala/kafka/server/DelayedFetch.scala
- core/src/main/scala/kafka/server/ReplicaManager.scala
> perf: allocate less in `readFromLocalLogV2`

- metadata/src/test/java/org/apache/kafka/image/ImageDowngradeTest.java
HI here is my fix for issue#657, just adding more information in expected output.
> fix(tests): Fix org.apache.kafka.image.ImageDowngradeTest

- build.gradle
- gradle/dependencies.gradle
- settings.gradle
> chore: source dependency on s3stream

- .github/workflows/build.yml
- build.gradle
- shell/src/main/java/org/apache/kafka/shell/MetadataNodeManager.java
- shell/src/test/java/org/apache/kafka/shell/ExtMetadataNodeManagerTest.java
> feat(tool): Support automq custom records parsing in metadata shell

- core/src/main/scala/kafka/Kafka.scala
- kshell-sdk/src/main/java/com/automq/s3shell/sdk/auth/CredentialsProviderHolder.java
- kshell-sdk/src/main/java/com/automq/s3shell/sdk/model/S3Url.java
Let kshell to init holder. Attention that kshell should be ready in open core to init holder
> fix: let kshell init holder

- core/src/main/java/kafka/s3shell/util/S3ShellPropUtil.java
Now we no need to reset env because even open core also get ak/sk from credential privder holder
> fix: support ecs role

- core/src/main/scala/kafka/log/streamaspect/ElasticLogManager.scala
- core/src/main/scala/kafka/log/streamaspect/ElasticLogSegment.scala
- core/src/main/scala/kafka/log/streamaspect/ElasticTimeIndex.scala
- core/src/main/scala/kafka/server/KafkaApis.scala
- core/src/test/java/kafka/log/streamaspect/ElasticTimeIndexTest.java
- core/src/test/java/kafka/log/streamaspect/ElasticTransactionIndexTest.java
- isolate timeindex api handle thread
- add timeindex cache from append
- fix ElasticTimeIndex bug
> feat(log): timeindex api thread isolation

- core/src/main/scala/kafka/server/ReplicaManager.scala
related issues: https://github.com/AutoMQ/automq-for-kafka/issues/437
> fix(logger): treat DuplicateSequenceException as expected

- tools/src/main/java/org/apache/kafka/tools/automq/GenerateConfigFileCmd.java
> fix: rename broker-address to broker-list

- core/src/main/scala/kafka/log/streamaspect/ElasticProducerStateManager.scala
- core/src/main/scala/kafka/log/streamaspect/ElasticUnifiedLog.scala
close https://github.com/AutoMQ/automq-for-kafka/issues/798
> fix(issues798): checkpoint NPE

- metadata/src/main/java/org/apache/kafka/controller/stream/S3ObjectControlManager.java
- metadata/src/main/java/org/apache/kafka/controller/stream/StreamControlManager.java
- metadata/src/test/java/org/apache/kafka/controller/StreamControlManagerTest.java
close https://github.com/AutoMQ/automq-for-kafka/issues/806
> fix(issues806): stream object leak

- core/src/main/scala/kafka/log/stream/s3/ConfigUtils.java
- core/src/main/scala/kafka/server/KafkaConfig.scala
> chore: rename s3ObjectRetention* to s3ObjectDeleteRetention for a more precise description

- core/src/main/scala/kafka/log/streamaspect/ElasticTransactionIndex.scala
close https://github.com/AutoMQ/automq-for-kafka/issues/817
> fix(issues817): txn index fetch out of bound

- core/src/main/scala/kafka/server/ReplicaManager.scala
> fix(ReplicaManager): fix memory leak caused by uncaught exception

- clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java
- clients/src/main/java/org/apache/kafka/common/network/Selector.java
close https://github.com/AutoMQ/automq-for-kafka/issues/826
> fix(issues826): fix consume records leak in closing channel

- core/src/main/scala/kafka/log/streamaspect/ElasticLog.scala
- core/src/main/scala/kafka/server/LogDirFailureChannel.scala
close https://github.com/AutoMQ/automq-for-kafka/issues/840
> fix: log permanet fail

- .github/workflows/nightly-extra-e2e.yml
- .github/workflows/nightly-main-e2e.yml
> ci: skip nightly schedule on forks

- docker/telemetry/grafana/provisioning/dashboards/Developer/detailed.json
- docker/telemetry/grafana/provisioning/dashboards/User/cluster.json
- docker/telemetry/grafana/provisioning/dashboards/User/group.json
- docker/telemetry/grafana/provisioning/dashboards/User/topic.json
- deduplication for consumer lag calculation on partition reassignment
- add get/put object avg latency panels
> fix(telemetry): refine grafana dashboard

- metadata/src/main/java/org/apache/kafka/controller/stream/StreamControlManager.java
https://github.com/AutoMQ/automq-for-kafka/issues/871
> feat(issues871): log request info for stream object compaction

- build.gradle
- clients/src/main/java/org/apache/kafka/common/config/TopicConfig.java
- metadata/src/main/java/org/apache/kafka/controller/ReplicationControlManager.java
- metadata/src/main/java/org/apache/kafka/controller/stream/S3ObjectControlManager.java
- metadata/src/test/java/org/apache/kafka/controller/PartitionChangeBuilderS3Test.java
- metadata/src/test/java/org/apache/kafka/controller/S3ObjectControlManagerTest.java
Ensure all unit tests with the tag "S3Unit" in the metadata module pass.
> fix(metadata): fix metadata tests

- tools/src/main/java/org/apache/kafka/tools/automq/GenerateS3UrlCmd.java
- tools/src/main/java/org/apache/kafka/tools/automq/GenerateStartCmdCmd.java
> fix(tools): endpoint compatibility includes HTTP protocol

- config/kraft/broker.properties
- config/kraft/server.properties
- core/src/main/scala/kafka/Kafka.scala
- core/src/main/scala/kafka/server/KafkaConfig.scala
- kshell-sdk/src/main/resources/template/broker.properties
- kshell-sdk/src/main/resources/template/server.properties
- s3stream/src/main/java/com/automq/stream/s3/ByteBufAlloc.java
- s3stream/src/main/java/com/automq/stream/s3/ByteBufAllocPolicy.java
- s3stream/src/main/java/com/automq/stream/s3/compact/CompactionManager.java
- s3stream/src/test/java/com/automq/stream/s3/compact/CompactionTestBase.java
- s3stream/src/test/java/com/automq/stream/s3/compact/CompactionUploaderTest.java
- s3stream/src/test/java/com/automq/stream/s3/compact/CompactionUtilTest.java
Same with https://github.com/AutoMQ/automq-for-kafka/pull/900 and https://github.com/AutoMQ/automq-for-rocketmq/pull/957
> feat(s3stream): policies of allocating memory

- bin/kafka-server-start.sh
- config/kraft/broker.properties
- config/kraft/server.properties
- core/src/main/scala/kafka/Kafka.scala
- core/src/main/scala/kafka/server/KafkaConfig.scala
- kshell-sdk/src/main/resources/template/broker.properties
- kshell-sdk/src/main/resources/template/server.properties
The same as https://github.com/AutoMQ/automq-for-kafka/pull/946
> feat(config): auto memory adaptation

- core/src/main/scala/kafka/admin/S3TestCommand.scala
- core/src/main/scala/kafka/log/stream/s3/ConfigUtils.java
- core/src/main/scala/kafka/log/stream/s3/DefaultS3Client.java
- core/src/main/scala/kafka/server/KafkaConfig.scala
- metadata/src/main/java/org/apache/kafka/controller/QuorumController.java
> feat(config): add a switch on tagging

- core/src/main/scala/kafka/Kafka.scala
- core/src/main/scala/kafka/server/KafkaConfig.scala
> fix(config): adjust configs in `KafkaConfig` rather than `Kafka`

- core/src/main/resources/jmx/rules/common.yaml
- docker/telemetry/grafana/provisioning/dashboards/Developer/detailed.json
> feat(metrics): support kraft related metrics

- core/src/main/scala/kafka/coordinator/group/CoordinatorLoaderImpl.scala
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/runtime/CoordinatorRuntime.java
- tests/kafkatest/tests/client/consumer_test.py
- tests/kafkatest/tests/core/consume_bench_test.py
close https://github.com/AutoMQ/automq/issues/978
> fix(test): fix new group coordinator load

- clients/src/main/java/org/apache/kafka/common/protocol/Errors.java
close https://github.com/AutoMQ/automq/issues/983
> fix(common): get cause NPE

- s3stream/src/main/java/com/automq/stream/s3/ObjectReader.java
- s3stream/src/main/java/com/automq/stream/s3/S3Stream.java
…009)"
revert experimental change
> revert(s3stream): revert bypass slow read throttle

- core/src/main/scala/kafka/log/UnifiedLog.scala
- core/src/main/scala/kafka/log/streamaspect/ElasticLog.scala
- core/src/main/scala/kafka/server/LogDirFailureChannel.scala
close https://github.com/AutoMQ/automq/issues/1058
> fix(issues1058): clear offline mark before reopen

- metadata/src/main/java/org/apache/kafka/controller/stream/S3ObjectControlManager.java
- metadata/src/test/java/org/apache/kafka/controller/S3ObjectControlManagerTest.java
close https://github.com/AutoMQ/automq/issues/1060
> fix(issues1060): only allow one cleanup task infight

- metadata/src/main/java/org/apache/kafka/controller/stream/S3StreamMetadata.java
- metadata/src/main/java/org/apache/kafka/controller/stream/StreamControlManager.java
> fix(controller): check continuity after redundancy in `commitStreamSetObject`

- metadata/src/test/java/org/apache/kafka/controller/StreamControlManagerTest.java
test for #1057
the same as #1064
> test(controller): commit the same stream set object or stream object

- s3stream/src/main/java/com/automq/stream/s3/S3StreamClient.java
- s3stream/src/test/java/com/automq/stream/s3/S3StreamClientTest.java
close https://github.com/AutoMQ/automq/issues/1069
> fix(issues1069): stream client shutdown await opening stream close

- core/src/main/scala/kafka/network/RequestChannel.scala
https://github.com/AutoMQ/automq/issues/1078
> fix(issues1078): fix RequestChannel shutdown blocking

- s3stream/pom.xml
> fix(maven): correct the maven build system for s3stream

- connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/AutoMQIdentityReplicationPolicy.java
> feat(MM2): allow customizing MM2 offset-syncs/checkpoints/heartbeats topic easily

- config/connect-log4j.properties
- config/log4j.properties
- tests/kafkatest/services/kafka/templates/log4j.properties
* Total disk usage: 5,080MB (less than 5GB)
* Details：
> build(issues1033): switch log appender from DailyRollingFileAppender to RollingFileAppender

- s3stream/src/main/java/com/automq/stream/s3/operator/DefaultS3Operator.java
- close https://github.com/AutoMQ/automq/issues/1097
- major change: #uploadPartCopy0
> feat(issues1097): increase api call timeout after timeout

- s3stream/src/main/java/com/automq/stream/s3/operator/DefaultS3Operator.java
The same as https://github.com/AutoMQ/automq/pull/1098
> feat(issues1097): increase api call timeout after timeout (#1098)

- build.gradle
> fix(gradle): specify the classifier for netty-tcnative

- core/src/main/scala/kafka/log/streamaspect/cache/FileCache.java
- s3stream/src/main/java/com/automq/stream/s3/ObjectReader.java
- s3stream/src/main/java/com/automq/stream/s3/cache/BlockCache.java
- s3stream/src/main/java/com/automq/stream/s3/cache/LRUCache.java
- s3stream/src/main/java/com/automq/stream/s3/cache/ReadAheadManager.java
- s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/AsyncSemaphore.java
- s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/DataBlock.java
- s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/DataBlockCache.java
- s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/EventLoopSafe.java
- s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/ReadStatusChangeListener.java
- s3stream/src/test/java/com/automq/stream/s3/cache/BlockCacheTest.java
- s3stream/src/test/java/com/automq/stream/s3/cache/blockcache/DataBlockCacheTest.java
part of https://github.com/AutoMQ/automq/issues/1087
> feat(issues1087): add data block cache

- s3stream/src/main/java/com/automq/stream/s3/ObjectReader.java
- s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/DataBlock.java
- s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/DataBlockCache.java
- s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/StreamReader.java
- s3stream/src/main/java/com/automq/stream/s3/operator/MemoryS3Operator.java
- s3stream/src/test/java/com/automq/stream/s3/cache/blockcache/MockObject.java
- s3stream/src/test/java/com/automq/stream/s3/cache/blockcache/StreamReaderTest.java
part of https://github.com/AutoMQ/automq/issues/1087
> feat(issues1087): add stream reader

- core/src/main/scala/kafka/log/stream/s3/ControllerKVClient.java
fix the ControllerKVClient.putKV method always return null, should return the task feature.
> fix(s3): ControllerKVClient putKV should return result

- core/src/main/scala/kafka/log/stream/s3/DefaultS3Client.java
- s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/AsyncSemaphore.java
- s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/DataBlock.java
- s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/DataBlockCache.java
- s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/StreamReader.java
- s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/StreamReaders.java
- s3stream/src/main/java/com/automq/stream/utils/LogSuppressor.java
- s3stream/src/main/java/com/automq/stream/utils/Systems.java
final part of https://github.com/AutoMQ/automq/issues/1087
> feat(issues1087): add stream readers

- s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/AsyncSemaphore.java
- s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/DataBlockCache.java
- s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/StreamReader.java
- s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/StreamReaders.java
- s3stream/src/main/java/com/automq/stream/utils/threads/EventLoop.java
- s3stream/src/test/java/com/automq/stream/s3/cache/blockcache/DataBlockCacheTest.java
- s3stream/src/test/java/com/automq/stream/s3/cache/blockcache/StreamReaderTest.java
fix https://github.com/AutoMQ/automq/issues/1087#issuecomment-2052725104
> fix(issues1087): event loop reject task after a task fail 

- core/src/main/scala/kafka/log/stream/s3/failover/DefaultFailoverFactory.java
- core/src/main/scala/kafka/log/stream/s3/metadata/StreamMetadataManager.java
- core/src/main/scala/kafka/log/stream/s3/objects/ControllerObjectManager.java
- s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/DataBlockCache.java
- s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/StreamReader.java
- s3stream/src/main/java/com/automq/stream/s3/exceptions/AutoMQException.java
- s3stream/src/main/java/com/automq/stream/s3/exceptions/BlockNotContinuousException.java
- s3stream/src/main/java/com/automq/stream/s3/exceptions/ObjectNotExistException.java
- s3stream/src/main/java/com/automq/stream/s3/memory/MemoryMetadataManager.java
- s3stream/src/main/java/com/automq/stream/s3/objects/ObjectManager.java
- s3stream/src/test/java/com/automq/stream/s3/cache/blockcache/StreamReaderTest.java
- fix https://github.com/AutoMQ/automq/issues/1087#issuecomment-2053643755
> fix(issues1087): fix long running issues

- s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/DataBlock.java
- s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/DataBlockCache.java
- s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/StreamReader.java
- s3stream/src/test/java/com/automq/stream/s3/cache/blockcache/StreamReaderTest.java
https://github.com/AutoMQ/automq/issues/1087
> fix(issues1087): fix object not exist handle

- metadata/src/main/java/org/apache/kafka/metadata/PartitionRegistration.java
https://github.com/AutoMQ/automq/issues/1127
> fix(issues1127): fix 1.0 to 1.1-rc0 launch fail

- s3stream/src/main/java/com/automq/stream/s3/ObjectReader.java
- s3stream/src/main/java/com/automq/stream/utils/Threads.java
- s3stream/src/test/java/com/automq/stream/s3/compact/CompactionAnalyzerTest.java
close https://github.com/AutoMQ/automq/issues/1142
> fix(issues1142): retry get index when object not exist

- s3stream/src/main/java/com/automq/stream/s3/compact/CompactionManager.java
> feat(issue1144): start next compaction in advance when needed

- metadata/src/main/java/org/apache/kafka/controller/stream/S3ObjectControlManager.java
close https://github.com/AutoMQ/automq/issues/1140
> fix(issues1140): fix S3ObjectControlManager NPE

- metadata/src/main/java/org/apache/kafka/controller/stream/S3ObjectControlManager.java
> Revert "fix(issues1140): fix S3ObjectControlManager NPE"

- s3stream/src/main/java/com/automq/stream/s3/operator/DefaultS3Operator.java
Change the checksum algorithm for the S3 client to reduce CPU usage.
> feat(s3stream): change the checksum algorithm to crc32c

- metadata/src/main/java/org/apache/kafka/controller/stream/S3ObjectControlManager.java
close https://github.com/AutoMQ/automq/issues/1171
> feat(issues1171): improve objects deletion performance

- metadata/src/main/java/org/apache/kafka/image/S3StreamsMetadataImage.java
- metadata/src/main/java/org/apache/kafka/metadata/stream/S3StreamSetObject.java
- metadata/src/test/java/org/apache/kafka/image/S3StreamsMetadataImageTest.java
- Substitute binary-search with hashmap
> feat(s3stream): speed up block cache get objects

- README.md
> chore: Update README.md for more accurate descriptions

- README.md
> chore: Update README.md for explanations for Kafka compatibility (#1191)

- README.md
> chore(readme): remove controller from the comparison table, and mark proxy of pulsar as optional

- metadata/src/main/java/org/apache/kafka/controller/stream/S3ObjectControlManager.java
> fix(issue1198): use timeline structure to avoid incorrect s3 object size

- clients/src/main/resources/common/message/CreateStreamsRequest.json
- clients/src/main/resources/common/message/CreateStreamsResponse.json
- core/src/main/scala/kafka/log/stream/s3/DefaultS3Client.java
- core/src/main/scala/kafka/log/stream/s3/failover/DefaultFailoverFactory.java
- core/src/main/scala/kafka/log/stream/s3/streams/ControllerStreamManager.java
- core/src/main/scala/kafka/log/streamaspect/ElasticLog.scala
- core/src/main/scala/kafka/log/streamaspect/ElasticLogStreamManager.java
- core/src/main/scala/kafka/log/streamaspect/LazyStream.java
- core/src/test/java/kafka/log/streamaspect/ElasticLogSegmentTest.java
- metadata/src/main/java/org/apache/kafka/controller/FeatureControlManager.java
- metadata/src/main/java/org/apache/kafka/controller/QuorumController.java
- metadata/src/main/java/org/apache/kafka/controller/stream/StreamControlManager.java
- metadata/src/main/java/org/apache/kafka/image/FeaturesImage.java
- metadata/src/main/java/org/apache/kafka/image/S3StreamMetadataDelta.java
- metadata/src/main/java/org/apache/kafka/image/S3StreamMetadataImage.java
- metadata/src/main/java/org/apache/kafka/image/node/automq/StreamImageNode.java
- metadata/src/main/java/org/apache/kafka/metadata/stream/StreamTags.java
- metadata/src/main/resources/common/metadata/S3StreamRecord.json
- metadata/src/test/java/org/apache/kafka/controller/StreamControlManagerTest.java
- metadata/src/test/java/org/apache/kafka/image/S3StreamMetadataImageTest.java
- s3stream/src/main/java/com/automq/stream/api/CreateStreamOptions.java
- s3stream/src/main/java/com/automq/stream/s3/S3StreamClient.java
- s3stream/src/main/java/com/automq/stream/s3/memory/MemoryMetadataManager.java
- s3stream/src/main/java/com/automq/stream/s3/streams/StreamManager.java
- server-common/src/main/java/org/apache/kafka/server/common/MetadataVersion.java
- server-common/src/main/java/org/apache/kafka/server/common/automq/AutoMQVersion.java
- part of https://github.com/AutoMQ/automq/issues/1174
> feat(s3stream): add tags to stream

- metadata/src/main/java/org/apache/kafka/controller/stream/StreamControlManager.java
> chore(controller): more logs

- .github/workflows/github-release.yml
> chore(cicd): removing site-docs file in GitHub release workflow

- core/src/main/scala/kafka/server/streamaspect/ElasticReplicaManager.scala
- part of https://github.com/AutoMQ/automq/issues/1169
- close https://github.com/AutoMQ/automq/issues/927
> feat(issues1169): prevent re-open partition when the broker is shutting down

- README.md
> feat(#1212): update readme，add alibaba cloud

- core/src/main/scala/kafka/server/streamaspect/ElasticKafkaApis.scala
- metadata/src/main/java/org/apache/kafka/controller/Controller.java
- metadata/src/main/java/org/apache/kafka/controller/QuorumController.java
- metadata/src/main/java/org/apache/kafka/controller/ReplicationControlManager.java
- metadata/src/main/java/org/apache/kafka/controller/stream/S3StreamMetadata.java
- metadata/src/main/java/org/apache/kafka/controller/stream/StreamControlManager.java
- metadata/src/main/java/org/apache/kafka/controller/stream/TopicDeletion.java
- metadata/src/main/java/org/apache/kafka/controller/stream/TopicDeletionManager.java
- metadata/src/test/java/org/apache/kafka/controller/S3ObjectControlManagerTest.java
- metadata/src/test/java/org/apache/kafka/controller/StreamControlManagerTest.java
- metadata/src/test/java/org/apache/kafka/controller/stream/TopicDeletionManagerTest.java
- server-common/src/main/java/org/apache/kafka/server/common/automq/AutoMQVersion.java
close https://github.com/AutoMQ/automq/issues/1174
> feat(issues1174): cleanup deleted topic by controller

- metadata/src/main/java/org/apache/kafka/controller/stream/StreamControlManager.java
close https://github.com/AutoMQ/automq/issues/1222
> fix(issues1222): fix #openStream resp nextOffset

- README.md
> chore: polish the lots of badges of readme

- core/src/main/scala/kafka/log/streamaspect/ElasticUnifiedLog.scala
- core/src/main/scala/kafka/log/streamaspect/PartitionStatusTracker.java
- core/src/main/scala/kafka/server/streamaspect/ElasticReplicaManager.scala
- part of https://github.com/AutoMQ/automq/issues/1153
> feat(issues1153): partition status self-check

- core/src/main/scala/kafka/log/streamaspect/PartitionStatusTracker.java
- docker/telemetry/grafana/provisioning/dashboards/User/broker.json
- server-common/src/main/java/org/apache/kafka/server/metrics/s3stream/S3StreamKafkaMetricsConstants.java
- server-common/src/main/java/org/apache/kafka/server/metrics/s3stream/S3StreamKafkaMetricsManager.java
close https://github.com/AutoMQ/automq/issues/1153
> feat(issues1153): add partition status statistics metrics

- core/src/main/scala/kafka/server/streamaspect/ElasticReplicaManager.scala
close https://github.com/AutoMQ/automq/issues/1248
> fix(issues1248): fix partition reassignment deadlock

- core/src/main/scala/kafka/log/streamaspect/DefaultOpenStreamChecker.java
- core/src/main/scala/kafka/log/streamaspect/PartitionStatusTracker.java
- core/src/main/scala/kafka/server/streamaspect/ElasticReplicaManager.scala
- core/src/test/java/kafka/log/streamaspect/PartitionStatusTrackerTest.java
close https://github.com/AutoMQ/automq/issues/1253
> fix(issues1253): fix duplicated Tracker#close fail

- core/src/main/scala/kafka/server/streamaspect/ElasticReplicaManager.scala
Clean up the consumption offset for the deleted partitions that do not belong to the current broker.
> fix(metadata): clean up the consumption offset for the deleted partitions

- README.md
> feat(issues1273): Optimize the readme to include more deployment options

- core/src/main/scala/kafka/server/KafkaRequestHandler.scala
- core/src/main/scala/kafka/server/streamaspect/ElasticReplicaManager.scala
> fix(core): clean potential leaked partition-level metrics periodically

- README.md
> feat(readme): add contact  #1286

- s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/StreamReader.java
close https://github.com/AutoMQ/automq/issues/1296
> fix(issues1296): fix potential stackoverflow

- s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/StreamReader.java
close https://github.com/AutoMQ/automq/issues/1300
> fix(issues1300): fix stream reader empty blocks

- s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/StreamReader.java
- s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/StreamReaders.java
close https://github.com/AutoMQ/automq/issues/1334
> fix(issues1334): fix stream reader endless looping

- checkstyle/suppressions.xml
- clients/src/main/resources/common/message/OpenStreamsRequest.json
- clients/src/main/resources/common/message/OpenStreamsResponse.json
- core/src/main/scala/kafka/log/stream/s3/streams/ControllerStreamManager.java
- core/src/main/scala/kafka/log/streamaspect/ElasticLog.scala
- core/src/main/scala/kafka/log/streamaspect/LazyStream.java
- metadata/src/main/java/org/apache/kafka/controller/stream/S3StreamMetadata.java
- metadata/src/main/java/org/apache/kafka/controller/stream/StreamControlManager.java
- s3stream/src/main/java/com/automq/stream/api/CreateStreamOptions.java
- s3stream/src/main/java/com/automq/stream/api/OpenStreamOptions.java
- s3stream/src/main/java/com/automq/stream/s3/S3StreamClient.java
- s3stream/src/main/java/com/automq/stream/s3/memory/MemoryMetadataManager.java
- s3stream/src/main/java/com/automq/stream/s3/streams/StreamManager.java
- s3stream/src/test/java/com/automq/stream/s3/S3StreamClientTest.java
The same as https://github.com/AutoMQ/automq/pull/1346
> feat(metadata): add missing tags for the old stream

- s3stream/src/main/java/com/automq/stream/s3/S3Stream.java
- s3stream/src/main/java/com/automq/stream/s3/network/AsyncNetworkBandwidthLimiter.java
- s3stream/src/test/java/com/automq/stream/s3/AsyncNetworkBandwidthLimiterTest.java
same as https://github.com/AutoMQ/automq/pull/1344
> fix(s3stream): refine network rate limiter for better precision (#1344)

- s3stream/src/main/java/com/automq/stream/utils/LogSuppressor.java
> fix(s3stream): fix variable typo

- metadata/src/main/java/org/apache/kafka/controller/QuorumController.java
> feat(core): log the block operation in controller event loop

- bin/kafka-server-start.sh
- s3stream/src/main/java/com/automq/stream/ByteBufSeqAlloc.java
- s3stream/src/main/java/com/automq/stream/s3/ByteBufAlloc.java
- s3stream/src/test/java/com/automq/stream/ByteBufSeqAllocTest.java
> perf(s3stream/allocator): increase trunk size of the netty allocator

- metadata/src/main/java/org/apache/kafka/image/TopicsDelta.java
- metadata/src/test/java/org/apache/kafka/image/TopicsImageTest.java
The same as https://github.com/AutoMQ/automq/pull/1358
> fix(issues1357): fix missing deletes when load from snapshot

- s3stream/src/main/java/com/automq/stream/s3/cache/DefaultS3BlockCache.java
> fix(s3stream): fix mismatched placeholders

- automq-shell/build.gradle
- automq-shell/src/main/java/com/automq/shell/AutoMQCLI.java
> feat(shell): add basic command for automq cli

- s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/StreamReader.java
close https://github.com/AutoMQ/automq/issues/1367
> fix(issues1367): stream reader prevent adding invalid blocks

- core/src/main/scala/kafka/raft/RaftManager.scala
- core/src/main/scala/kafka/server/KafkaServer.scala
- core/src/main/scala/kafka/server/SharedServer.scala
- core/src/main/scala/kafka/tools/TestRaftServer.scala
- core/src/test/scala/unit/kafka/raft/RaftManagerTest.scala
see https://issues.apache.org/jira/browse/KAFKA-14644
> fix(KAFKA-14644): Process should crash after failure in Raft IO thread (#13140)

- core/src/main/scala/kafka/server/AbstractFetcherThread.scala
- core/src/test/scala/unit/kafka/server/AbstractFetcherThreadTest.scala
- core/src/test/scala/unit/kafka/server/ReplicaFetcherThreadTest.scala
see https://issues.apache.org/jira/browse/KAFKA-14704
> fix(KAFKA-14704): Follower should truncate before incrementing high watermark

- s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/StreamReader.java
The same as https://github.com/AutoMQ/automq/pull/1382
> fix(cache): fix readhead fail when user read fast than readahead

- metadata/src/main/java/org/apache/kafka/image/loader/MetadataLoader.java
this is a partial fix of https://issues.apache.org/jira/browse/KAFKA-14857 due to conflict
> fix(metadata): fix broken logic on catching up check

- metadata/src/main/java/org/apache/kafka/image/loader/MetadataLoader.java
- metadata/src/test/java/org/apache/kafka/image/loader/MetadataLoaderTest.java
- metadata/src/test/java/org/apache/kafka/image/publisher/SnapshotGeneratorTest.java
- server-common/src/main/java/org/apache/kafka/queue/KafkaEventQueue.java
see https://issues.apache.org/jira/browse/KAFKA-14857
> fix(KAFKA-14857): Fix some MetadataLoader bugs

- core/src/main/scala/kafka/controller/streamaspect/client/s3/StreamClientFactory.java
- core/src/main/scala/kafka/log/stream/s3/ConfigUtils.java
- core/src/main/scala/kafka/log/stream/s3/DefaultS3Client.java
- core/src/main/scala/kafka/log/stream/s3/metadata/StreamMetadataManager.java
- core/src/main/scala/kafka/log/streamaspect/client/s3/ClientFactory.java
- core/src/main/scala/kafka/server/KafkaConfig.scala
> refactor(s3stream): remove `DefaultS3Client`'s dependency on `KafkaConfig`

- metadata/src/main/java/org/apache/kafka/controller/QuorumController.java
close https://github.com/AutoMQ/automq/issues/604
> fix(issues604): fix response size not match

- tools/src/main/java/org/apache/kafka/tools/automq/PerfCommand.java
- tools/src/main/java/org/apache/kafka/tools/automq/perf/PerfConfig.java
- tools/src/main/java/org/apache/kafka/tools/automq/perf/ProducerService.java
> feat(tools/perf): adjust send rate during warmup and catchup

- metadata/src/main/java/org/apache/kafka/controller/stream/StreamControlManager.java
- metadata/src/main/java/org/apache/kafka/image/DeltaMap.java
- metadata/src/main/java/org/apache/kafka/image/KVDelta.java
- metadata/src/main/java/org/apache/kafka/image/KVImage.java
- metadata/src/main/java/org/apache/kafka/image/S3ObjectsDelta.java
- metadata/src/main/java/org/apache/kafka/image/S3ObjectsImage.java
- metadata/src/main/java/org/apache/kafka/image/loader/MetadataLoader.java
- metadata/src/main/java/org/apache/kafka/image/node/automq/KVImageNode.java
- metadata/src/main/java/org/apache/kafka/image/node/automq/ObjectsImageNode.java
- metadata/src/main/java/org/apache/kafka/image/publisher/SnapshotGenerator.java
- metadata/src/test/java/org/apache/kafka/image/KVImageTest.java
- metadata/src/test/java/org/apache/kafka/image/MetadataImageTest.java
- metadata/src/test/java/org/apache/kafka/image/S3ObjectsImageTest.java
- cherry-pick from large scale optimize
> perf(metadata): use Timeline for objects image

- core/src/main/scala/kafka/log/streamaspect/cache/FileCache.java
- core/src/test/java/kafka/log/streamaspect/cache/FileCacheTest.java
You can just review the latest commit https://github.com/AutoMQ/automq/pull/1425/commits/8d5f0f339559e10aa5cd878be6bf4b72cc9c79b3
> perf(FileCache): avoid evicting too many blocks at once

- clients/src/main/resources/common/message/CommitStreamObjectRequest.json
- core/src/main/scala/kafka/log/stream/s3/objects/ControllerObjectManager.java
- metadata/src/main/java/org/apache/kafka/controller/QuorumController.java
- metadata/src/main/java/org/apache/kafka/controller/stream/S3ObjectControlManager.java
- metadata/src/test/java/org/apache/kafka/controller/S3ObjectControlManagerTest.java
- s3stream/src/main/java/com/automq/stream/s3/CompositeObject.java
- s3stream/src/main/java/com/automq/stream/s3/CompositeObjectReader.java
- s3stream/src/main/java/com/automq/stream/s3/CompositeObjectWriter.java
- s3stream/src/main/java/com/automq/stream/s3/ObjectReader.java
- s3stream/src/main/java/com/automq/stream/s3/S3StreamClient.java
- s3stream/src/main/java/com/automq/stream/s3/compact/CompactOperations.java
- s3stream/src/main/java/com/automq/stream/s3/compact/StreamObjectCompactor.java
- s3stream/src/main/java/com/automq/stream/s3/objects/CompactStreamObjectRequest.java
- s3stream/src/main/java/com/automq/stream/s3/operator/DefaultS3Operator.java
- s3stream/src/main/java/com/automq/stream/s3/operator/MemoryS3Operator.java
- s3stream/src/test/java/com/automq/stream/s3/compact/StreamObjectCompactorTest.java
- s3stream/src/test/java/com/automq/stream/s3/objects/ObjectManagerTest.java
- server-common/src/main/java/org/apache/kafka/server/common/automq/AutoMQVersion.java
Main Changes:
- StreamObjectCompactor$CompactByCompositeObject
> feat(s3stream): compact to composite object

- checkstyle/suppressions.xml
- core/src/main/scala/kafka/log/stream/s3/DefaultS3Client.java
- metadata/src/main/java/org/apache/kafka/controller/QuorumController.java
- metadata/src/main/java/org/apache/kafka/controller/stream/StreamClient.java
- s3stream/src/main/java/com/automq/stream/s3/DeltaWALUploadTask.java
- s3stream/src/main/java/com/automq/stream/s3/ObjectReader.java
- s3stream/src/main/java/com/automq/stream/s3/S3Storage.java
- s3stream/src/main/java/com/automq/stream/s3/S3StreamClient.java
- s3stream/src/main/java/com/automq/stream/s3/compact/StreamObjectCompactor.java
- s3stream/src/main/java/com/automq/stream/s3/operator/AbstractObjectStorage.java
- s3stream/src/main/java/com/automq/stream/s3/operator/AwsObjectStorage.java
- s3stream/src/main/java/com/automq/stream/s3/operator/MemoryObjectStorage.java
- s3stream/src/test/java/com/automq/stream/s3/DeltaWALUploadTaskTest.java
- s3stream/src/test/java/com/automq/stream/s3/compact/CompactionManagerTest.java
- s3stream/src/test/java/com/automq/stream/s3/compact/StreamObjectCompactorTest.java
> feat: add composite object test

- clients/src/main/java/org/apache/kafka/common/requests/s3/CloseStreamsResponse.java
- clients/src/main/java/org/apache/kafka/common/requests/s3/CreateStreamsResponse.java
- clients/src/main/java/org/apache/kafka/common/requests/s3/DeleteKVsResponse.java
- clients/src/main/java/org/apache/kafka/common/requests/s3/DeleteStreamsResponse.java
- clients/src/main/java/org/apache/kafka/common/requests/s3/DescribeStreamsResponse.java
- clients/src/main/java/org/apache/kafka/common/requests/s3/GetKVsResponse.java
- clients/src/main/java/org/apache/kafka/common/requests/s3/OpenStreamsResponse.java
- clients/src/main/java/org/apache/kafka/common/requests/s3/PutKVsResponse.java
- clients/src/main/java/org/apache/kafka/common/requests/s3/TrimStreamsResponse.java
fix https://github.com/AutoMQ/automq/issues/1488
> fix(api): fix channel isn't switch when encounter NOT_CONTROLLER

- .github/workflows/build_automq.yml
https://github.com/gradle/actions/blob/main/docs/wrapper-validation.md
> build(gradle): enable Gradle wrapper validation

- .editorconfig
EditorConfig allows contributors to set up their IDE-s to match the coding standard of automq.
From https://github.com/szepeviktor/github-repository-inspection
Based on the email sent by @vintagewang
> chore: Introduce EditorConfig

- metadata/src/main/java/org/apache/kafka/controller/stream/S3ObjectControlManager.java
- s3stream/src/main/java/com/automq/stream/s3/operator/AbstractObjectStorage.java
close https://github.com/AutoMQ/automq/issues/1527
> fix(issues1527): fix delete empty list

- metadata/src/main/java/org/apache/kafka/image/S3StreamsMetadataImage.java
> fix(issue1526): avoid completing future before search complete

- tools/src/main/java/org/apache/kafka/tools/automq/AutoMQKafkaAdminTool.java
- tools/src/main/java/org/apache/kafka/tools/automq/GenerateConfigFileCmd.java
- tools/src/main/java/org/apache/kafka/tools/automq/GenerateS3UrlCmd.java
- tools/src/main/java/org/apache/kafka/tools/automq/GenerateStartCmdCmd.java
> fix(issues1539): fix auto-kafka-admin.sh help information.

- tests/kafkatest/services/kafka/kafka.py
> feat(e2e): kafka.py JVM OPT uses parameter passing instead of fixed values.

- s3stream/src/main/java/com/automq/stream/s3/wal/exception/WALShutdownException.java
- s3stream/src/main/java/com/automq/stream/s3/wal/impl/block/SlidingWindowService.java
[issue](https://github.com/AutoMQ/automq/issues/1578)
> feat(wal): graceful shutdown optimization #1578

- metadata/src/main/java/org/apache/kafka/controller/stream/S3StreamMetadata.java
- metadata/src/main/java/org/apache/kafka/controller/stream/StreamControlManager.java
- metadata/src/test/java/org/apache/kafka/controller/stream/S3StreamMetadataTest.java
close https://github.com/AutoMQ/automq/issues/1608
> feat(issues1608): clean up useless range metadata

- core/src/main/scala/kafka/log/stream/s3/DefaultS3Client.java
- core/src/main/scala/kafka/log/stream/s3/objects/ControllerObjectManager.java
close https://github.com/AutoMQ/automq/issues/1619
> fix(s3stream): fix get the v0 automq version when recover

- .github/workflows/github-release.yml
- gradle.properties
Fix failed version check: https://github.com/AutoMQ/automq/actions/runs/10034322592/job/27728675931
The fix has been verified on the local machine.
> fix(build): fix version check for e2e test

- clients/src/main/resources/common/message/AutomqGetNodesResponse.json
- clients/src/main/resources/common/message/AutomqRegisterNodeRequest.json
- core/src/main/scala/kafka/server/streamaspect/ElasticControllerApis.scala
- core/src/test/java/kafka/test/MockController.java
- metadata/src/main/java/org/apache/kafka/controller/Controller.java
- metadata/src/main/java/org/apache/kafka/controller/QuorumController.java
- metadata/src/main/java/org/apache/kafka/controller/stream/DefaultNodeRuntimeInfoGetter.java
- metadata/src/main/java/org/apache/kafka/controller/stream/NodeControlManager.java
- metadata/src/main/java/org/apache/kafka/controller/stream/NodeMetadata.java
- metadata/src/main/java/org/apache/kafka/controller/stream/NodeMetadataCodec.java
- metadata/src/main/java/org/apache/kafka/controller/stream/NodeRuntimeInfoGetter.java
- metadata/src/main/java/org/apache/kafka/controller/stream/NodeRuntimeMetadata.java
- metadata/src/main/java/org/apache/kafka/controller/stream/NodeState.java
- metadata/src/main/java/org/apache/kafka/controller/stream/StreamControlManager.java
- metadata/src/main/java/org/apache/kafka/controller/stream/StreamRuntimeMetadata.java
- metadata/src/main/java/org/apache/kafka/controller/stream/TopicDeletionManager.java
- metadata/src/test/java/org/apache/kafka/controller/stream/NodeControlManagerTest.java
- metadata/src/test/java/org/apache/kafka/controller/stream/StreamControlManagerTest.java
- metadata/src/test/java/org/apache/kafka/controller/stream/StreamRuntimeMetadataTest.java
- metadata/src/test/java/org/apache/kafka/controller/stream/TopicDeletionManagerTest.java
- metadata/src/test/java/org/apache/kafka/image/NodeRuntimeMetadataImageTest.java
- metadata/src/test/java/org/apache/kafka/image/StreamRuntimeMetadataImageTest.java
Main changed code:
- NodeControlManager
- StreamControlManager.node2streams related code
> feat(controller): add node manager

- core/src/main/scala/kafka/log/stream/s3/DefaultS3Client.java
- core/src/main/scala/kafka/log/streamaspect/ElasticLogManager.scala
- core/src/main/scala/kafka/server/BrokerServer.scala
- The ApiVersionsRequest will get initial features[MINIMUM_KRAFT_VERSION] when cluster bootstrap.
> fix(s3stream): fix version get npe by change the s3stream load timing

- metadata/src/main/java/org/apache/kafka/controller/stream/S3ObjectControlManager.java
- metadata/src/main/java/org/apache/kafka/controller/stream/StreamControlManager.java
- metadata/src/test/java/org/apache/kafka/controller/stream/StreamControlManagerTest.java
close https://github.com/AutoMQ/automq/issues/1642
> fix(issues1642): fix bucket not match

- README.md
The primary correction was updating "Free trail" to "free trial" to fix a spelling error. This change improves the clarity and professionalism of the document.
No functional code changes were made, so no additional testing beyond standard proofreading was necessary. This update ensures that the documentation accurately reflects the intended message.
Given that the change is purely text-based and involves no modifications to the functionality of the system, no unit or integration tests were required. The focus was on a manual review to ensure the correctness of the documentation.
> docs: Correct spelling error in README.md

- s3stream/src/main/java/com/automq/stream/s3/cache/LogCache.java
[issue](https://github.com/AutoMQ/automq/issues/1683)
> feat(s3Stream): fix excessive  cache release in concurrent scenarios.

- metadata/src/main/java/org/apache/kafka/controller/BrokerHeartbeatManager.java
- metadata/src/main/java/org/apache/kafka/controller/stream/OverloadCircuitBreaker.java
- metadata/src/test/java/org/apache/kafka/controller/BrokerHeartbeatManagerTest.java
- metadata/src/test/java/org/apache/kafka/controller/stream/OverloadCircuitBreakerTest.java
close https://github.com/AutoMQ/automq/issues/1446
> feat(issues1446): avoid accidentally fence brokers when controller overload

- core/src/main/scala/kafka/log/streamaspect/DefaultOpenStreamChecker.java
- core/src/main/scala/kafka/server/metadata/KRaftMetadataCache.scala
close https://github.com/AutoMQ/automq/issues/1689
> fix(issues1689): retain image before use

- core/src/main/scala/kafka/server/streamaspect/ElasticReplicaManager.scala
> fix(core): Fix integer overflow in bytesNeed calculation

- s3stream/src/main/java/com/automq/stream/s3/S3Stream.java
- s3stream/src/main/java/com/automq/stream/s3/wal/impl/block/SlidingWindowService.java
background:
extract real exception
com.automq.stream.s3.S3Stream#append0
> feat(s3stream): extract real exception

- core/src/main/scala/kafka/log/streamaspect/ElasticLog.scala
close https://github.com/AutoMQ/automq/issues/1737
> fix(issues1737): log close await append callback complete

- core/src/main/scala/kafka/log/streamaspect/ElasticLog.scala
- core/src/main/scala/kafka/log/streamaspect/ElasticUnifiedLog.scala
close https://github.com/AutoMQ/automq/issues/1740
> fix(issues1740): fix log close await deadlock

- s3stream/src/main/java/com/automq/stream/s3/ObjectWriter.java
> fix(s3stream): make `ObjectWriter#write` synchronized

- core/src/main/java/kafka/autobalancer/goals/Goal.java
- core/src/main/java/kafka/autobalancer/model/AbstractInstanceUpdater.java
- core/src/main/java/kafka/autobalancer/model/BrokerUpdater.java
- core/src/main/java/kafka/autobalancer/model/ClusterModel.java
- core/src/main/java/kafka/autobalancer/model/TopicPartitionReplicaUpdater.java
- core/src/test/java/kafka/autobalancer/goals/GoalTestBase.java
- core/src/test/java/kafka/autobalancer/goals/ResourceUsageDistributionGoalTest.java
- core/src/test/java/kafka/autobalancer/model/ClusterModelTest.java
same as https://github.com/AutoMQ/automq/pull/1760
> feat(auto_balancer): preserve out-of-sync  broker and partition in cluster model snapshot

- core/src/main/java/kafka/autobalancer/model/BrokerUpdater.java
- core/src/main/java/kafka/autobalancer/model/ClusterModel.java
same as https://github.com/AutoMQ/automq/pull/1771
> feat(auto_balancer): allow change broker rack on register (#1771)

- .github/workflows/nightly-main-e2e.yml
- tests/kafkatest/automq/__init__.py
- tests/kafkatest/automq/autobalancer_test.py
- tests/kafkatest/automq/automq_e2e_util.py
- tests/kafkatest/automq/compaction_test.py
- tests/kafkatest/automq/memory_occupancy_test.py
- tests/kafkatest/automq/quota_test.py
- tests/kafkatest/automq/s3_leakage_test.py
- tests/suites/main_kos_test_suite6.yml
**Purpose of Use Cases**
Test the correctness of data within each Compaction lifecycle.
**Use case description**
【1】 After Stream Set Object Compaction
【2】 After passing through Stream Set Object Compaction、Stream Object Compaction MAJOR_V1
【3】 After passing through Stream Set Object Compaction、Stream Object Compaction MINOR_V1
【4】 After Stream Object Compaction MAJOR_V1
【5】 After passing through Stream Object Compaction MINOR_V1
**Specific process**
1. Write data, at this time the threshold is low enough to ensure that the data can be flushed into S3, generating stream set object+stream object
If a stream set object comparison is required, wait for the stream set object comparison to be performed and convert all stream set objects into stream objects
3. Write data again to generate …
> test(e2e): add compaction test.

- metadata/src/main/java/org/apache/kafka/controller/ClusterControlManager.java
- metadata/src/main/java/org/apache/kafka/controller/ReplicationControlManager.java
- metadata/src/main/java/org/apache/kafka/controller/es/LoadAwarePartitionLeaderSelector.java
- metadata/src/test/java/org/apache/kafka/controller/es/LoadAwarePartitionLeaderSelectorTest.java
same as https://github.com/AutoMQ/automq/pull/1778
> feat(auto_balancer): assign partitions within rack on broker fence (#1778)

- s3stream/src/main/java/com/automq/stream/s3/DeltaWALUploadTask.java
- s3stream/src/main/java/com/automq/stream/s3/ObjectWriter.java
- s3stream/src/main/java/com/automq/stream/utils/AsyncRateLimiter.java
- s3stream/src/test/java/com/automq/stream/s3/ObjectWriterTest.java
close https://github.com/AutoMQ/automq/issues/1784
> fix(issues1784): fix upload burst cause object index out of order

- build.gradle
- clients/src/main/java/org/apache/kafka/common/utils/BufferSupplier.java
- clients/src/test/java/org/apache/kafka/common/utils/BufferSupplierTest.java
- raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java
> perf: use netty buffer to pool memory

- core/src/main/java/kafka/autobalancer/model/ClusterModel.java
- core/src/main/scala/kafka/server/ReplicaManager.scala
- server-common/src/main/java/org/apache/kafka/server/metrics/s3stream/PartitionCountDistribution.java
- server-common/src/main/java/org/apache/kafka/server/metrics/s3stream/S3StreamKafkaMetricsConstants.java
- server-common/src/main/java/org/apache/kafka/server/metrics/s3stream/S3StreamKafkaMetricsManager.java
same as https://github.com/AutoMQ/automq/pull/1782
> feat(metrics): add topic partition distribution metric (#1782)

- s3stream/src/main/java/com/automq/stream/s3/wal/impl/object/RecordAccumulator.java
> fix(s3stream): fix dead lock issue

- core/src/main/scala/kafka/log/stream/s3/streams/ControllerStreamManager.java
- metadata/src/main/java/org/apache/kafka/controller/stream/StreamControlManager.java
The same as https://github.com/AutoMQ/automq/pull/1819
> chore(logger): move trim log to broker

- raft/src/main/java/org/apache/kafka/raft/QuorumConfig.java
The same as https://github.com/AutoMQ/automq/pull/1823
> chore(config): change quorum default timeout to 5s

- .github/workflows/e2e-run.yml
- .github/workflows/nightly-extra-e2e.yml
- .github/workflows/nightly-main-e2e.yml
The same as https://github.com/AutoMQ/automq/pull/1825
> chore(workflows): e2e support release runner

- s3stream/src/main/java/com/automq/stream/s3/wal/impl/block/BlockWALService.java
- s3stream/src/main/java/com/automq/stream/s3/wal/impl/block/SlidingWindowService.java
- s3stream/src/main/java/com/automq/stream/s3/wal/util/WALChannel.java
> fix(s3strea/wal): handle `IOException` during flushing WAL header

- s3stream/src/main/java/com/automq/stream/s3/cache/AsyncLRUCache.java
- s3stream/src/main/java/com/automq/stream/s3/cache/ObjectReaderLRUCache.java
- s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/DefaultObjectReaderFactory.java
- s3stream/src/main/java/com/automq/stream/s3/index/NodeRangeIndexCache.java
- s3stream/src/main/java/com/automq/stream/s3/metrics/S3StreamMetricsConstant.java
- s3stream/src/main/java/com/automq/stream/s3/metrics/S3StreamMetricsManager.java
- s3stream/src/main/java/com/automq/stream/s3/metrics/stats/AsyncLRUCacheStats.java
- s3stream/src/test/java/com/automq/stream/s3/cache/AsyncLRUCacheTest.java
- s3stream/src/test/java/com/automq/stream/s3/cache/ObjectReaderLRUCacheTest.java
pick from https://github.com/AutoMQ/automq/pull/1829 to release 1.2
> feat(s3stream): add AsyncLRUCache metric (#1829)

- s3stream/src/main/java/com/automq/stream/s3/failover/StorageFailureHandlerChain.java
cherry-pick: https://github.com/AutoMQ/automq/pull/1838
> fix(s3stream): fix storage failure handle deadlock

- metadata/src/main/java/org/apache/kafka/controller/QuorumController.java
- metadata/src/main/java/org/apache/kafka/controller/stream/TopicDeletionManager.java
- metadata/src/test/java/org/apache/kafka/controller/stream/TopicDeletionManagerTest.java
- s3stream/src/main/java/com/automq/stream/s3/metadata/ObjectUtils.java
close https://github.com/AutoMQ/automq/issues/1842
> feat(issues1842): cleanup metastream kv after deleting topic

- s3stream/src/main/java/com/automq/stream/s3/S3Storage.java
cherry-pick https://github.com/AutoMQ/automq/pull/1845
> fix(s3stream): error callback

- s3stream/src/main/java/com/automq/stream/s3/S3Storage.java
> fix(revert): error callback

- metadata/src/main/java/org/apache/kafka/image/S3StreamsMetadataImage.java
- s3stream/src/main/java/com/automq/stream/s3/cache/AsyncLRUCache.java
- s3stream/src/main/java/com/automq/stream/s3/index/NodeRangeIndexCache.java
- s3stream/src/test/java/com/automq/stream/s3/index/NodeRangeIndexCacheTest.java
same as https://github.com/AutoMQ/automq/pull/1847
> feat(metadata): limit sparse index cache update interval

- s3stream/src/main/java/com/automq/stream/s3/S3Stream.java
- s3stream/src/main/java/com/automq/stream/s3/S3StreamClient.java
cherry-pick https://github.com/AutoMQ/automq/pull/1854
> feat(s3stream): support call #close(force=true) after #close(force=false)

- core/src/main/scala/kafka/log/stream/s3/metadata/StreamMetadataManager.java
- s3stream/src/main/java/com/automq/stream/s3/index/LocalStreamRangeIndexCache.java
- s3stream/src/test/java/com/automq/stream/s3/index/LocalStreamRangeIndexCacheTest.java
same as https://github.com/AutoMQ/automq/pull/1856
> feat(metadata): prune invalid sparse index with image on startup

- metadata/src/main/java/org/apache/kafka/image/S3StreamsMetadataImage.java
same as https://github.com/AutoMQ/automq/pull/1872
> fix(metadata): catch exception to prevent unnecessary error log

- tests/kafkatest/services/streams.py
The same as https://github.com/AutoMQ/automq/pull/1892
> chore(logger): change e2e streams log level to INFO

- s3stream/src/main/java/com/automq/stream/FixedSizeByteBufPool.java
- s3stream/src/main/java/com/automq/stream/s3/wal/common/RecordHeader.java
- s3stream/src/main/java/com/automq/stream/s3/wal/impl/object/ObjectWALService.java
- s3stream/src/main/java/com/automq/stream/s3/wal/util/WALUtil.java
- s3stream/src/test/java/com/automq/stream/s3/wal/impl/block/BlockWALServiceTest.java
- s3stream/src/test/java/com/automq/stream/s3/wal/impl/object/ObjectWALServiceTest.java
> perf(s3stream): optimize the critical section in s3 wal (#1880)

- s3stream/src/main/java/com/automq/stream/s3/wal/impl/block/BlockImpl.java
- s3stream/src/test/java/com/automq/stream/s3/wal/impl/block/BlockImplTest.java
> fix(s3stream/wal): fix memory leak

- core/src/main/java/kafka/autobalancer/detector/AnomalyDetector.java
- core/src/main/java/kafka/autobalancer/model/BrokerUpdater.java
- core/src/main/java/kafka/autobalancer/model/TopicPartitionReplicaUpdater.java
- metadata/src/main/java/org/apache/kafka/image/S3StreamsMetadataImage.java
- s3stream/src/main/java/com/automq/stream/s3/S3Storage.java
- s3stream/src/main/java/com/automq/stream/s3/S3Stream.java
- s3stream/src/main/java/com/automq/stream/s3/cache/LogCache.java
- s3stream/src/main/java/com/automq/stream/s3/index/LocalStreamRangeIndexCache.java
- s3stream/src/main/java/com/automq/stream/s3/index/NodeRangeIndexCache.java
- s3stream/src/main/java/com/automq/stream/s3/metrics/S3StreamMetricsConstant.java
- s3stream/src/main/java/com/automq/stream/s3/metrics/S3StreamMetricsManager.java
- s3stream/src/main/java/com/automq/stream/s3/metrics/TimerUtil.java
- s3stream/src/main/java/com/automq/stream/s3/metrics/stats/MetadataStats.java
- s3stream/src/main/java/com/automq/stream/s3/operator/AbstractObjectStorage.java
- s3stream/src/main/java/com/automq/stream/s3/wal/impl/block/BlockImpl.java
- s3stream/src/main/java/com/automq/stream/s3/wal/impl/block/BlockWALService.java
- s3stream/src/main/java/com/automq/stream/s3/wal/impl/block/SlidingWindowService.java
same as https://github.com/AutoMQ/automq/pull/1902
> feat(metadata): add metrics for sparse index cache monitor

- build.gradle
- s3stream/src/main/java/com/automq/stream/s3/operator/AbstractObjectStorage.java
- s3stream/src/main/java/com/automq/stream/s3/operator/AwsObjectStorage.java
- s3stream/src/test/java/com/automq/stream/s3/operator/ProxyWriterTest.java
> feat(s3stream): support change checksum algorithm

- tests/kafkatest/version.py
fix `TC_PATHS="tests/kafkatest/tests/streams/streams_upgrade_test.py::StreamsUpgradeTest.test_upgrade_downgrade_state_updater" bash tests/docker/run_tests.sh`
> fix(test): set dev version to 3.8.0

- .github/workflows/github-nightly-release.yml
> chore: add nightly release for automq

- .github/workflows/github-nightly-release.yml
> chore: polish the nightly release

- .github/workflows/github-nightly-release.yml
> chore: make the nightly release as a pre release

- s3stream/src/main/java/com/automq/stream/s3/operator/AbstractObjectStorage.java
> feat(s3stream): limit the inflight fast retry request count

- s3stream/src/main/java/com/automq/stream/s3/Config.java
- s3stream/src/main/java/com/automq/stream/s3/compact/CompactionManager.java
- s3stream/src/main/java/com/automq/stream/s3/network/ThrottleStrategy.java
- s3stream/src/test/java/com/automq/stream/s3/AsyncNetworkBandwidthLimiterTest.java
The same as https://github.com/AutoMQ/automq/pull/1935
> feat(s3stream): ensure compaction could be executed (#1935)

- s3stream/src/main/java/com/automq/stream/Version.java
> docs(s3stream/version): statement of features supported by S3Stream V1

- s3stream/src/main/java/com/automq/stream/s3/wal/impl/object/ObjectWALService.java
> fix(s3stream): fix buffer leak

- s3stream/src/main/java/com/automq/stream/ByteBufSeqAlloc.java
adjust the default size of huge buf
> fix(bufAlloc): adjust the default size

- README.md
> feat(readme): update aws marketplace url(#1936)

- core/src/main/scala/kafka/log/stream/s3/objects/ControllerObjectManager.java
cherry-pick https://github.com/AutoMQ/automq/pull/1961
> fix(issues1960): allow UNSET attributes for version 1.1

- s3stream/src/main/java/com/automq/stream/s3/S3Stream.java
- s3stream/src/main/java/com/automq/stream/s3/network/ThrottleStrategy.java
- s3stream/src/main/java/com/automq/stream/s3/operator/AbstractObjectStorage.java
priority after change: produce > tail > compaction > catch up
> feat(s3stream): add tail read throttle strategy

- README.md
add introduction and BYOC terraform installation's video for AutoMQ
> Update README.md with new videos

- core/src/main/scala/kafka/log/streamaspect/ElasticLogSegmentManager.java
- core/src/test/java/kafka/log/streamaspect/ElasticLogSegmentManagerTest.java
> fix(log): use the same view to calculate trim offsets

- core/src/main/scala/kafka/log/streamaspect/ElasticLogMeta.java
> chore: beautify `ElasticLogMeta` in logs

- s3stream/src/main/java/com/automq/stream/utils/IdURI.java
> chore(util): implement `IdURI#toString`

- core/src/main/scala/kafka/network/SocketServer.scala
close https://github.com/AutoMQ/automq/issues/1999
> fix(issues1999): fix Processor.channelContexts memory leak

- core/src/main/scala/kafka/server/streamaspect/ElasticReplicaManager.scala
> perf(DelayedFetch): only try to fast read on complete a delayed fetch

- clients/src/main/java/org/apache/kafka/common/protocol/ApiKeys.java
- clients/src/main/java/org/apache/kafka/common/requests/AbstractRequest.java
- clients/src/main/java/org/apache/kafka/common/requests/AbstractResponse.java
- clients/src/main/java/org/apache/kafka/common/requests/s3/AutomqZoneRouterRequest.java
- clients/src/main/java/org/apache/kafka/common/requests/s3/AutomqZoneRouterResponse.java
- clients/src/main/resources/common/message/AutomqZoneRouterRequest.json
- clients/src/main/resources/common/message/AutomqZoneRouterResponse.json
- core/src/main/java/kafka/automq/zonerouter/ClientIdKey.java
- core/src/main/java/kafka/automq/zonerouter/ClientIdMetadata.java
- core/src/main/java/kafka/automq/zonerouter/NoopProduceRouter.java
- core/src/main/java/kafka/automq/zonerouter/ProduceRouter.java
- core/src/main/scala/kafka/network/RequestConvertToJson.scala
- core/src/main/scala/kafka/server/BrokerServer.scala
- core/src/main/scala/kafka/server/KafkaApis.scala
- core/src/main/scala/kafka/server/MetadataCache.scala
- core/src/main/scala/kafka/server/metadata/KRaftMetadataCache.scala
- core/src/main/scala/kafka/server/metadata/ZkMetadataCache.scala
- core/src/main/scala/kafka/server/streamaspect/ElasticKafkaApis.scala
- core/src/main/scala/kafka/server/streamaspect/ElasticReplicaManager.scala
- s3stream/src/main/java/com/automq/stream/s3/metadata/ObjectUtils.java
- s3stream/src/main/java/com/automq/stream/utils/Systems.java
- s3stream/src/main/java/com/automq/stream/utils/URIUtils.java
Main changes:
- Add Produce & Metadata request interceptor
- Add AutomqZoneRouter API
> feat(api): add produce interceptor

- metadata/src/main/java/org/apache/kafka/controller/stream/StreamControlManager.java
- metadata/src/main/java/org/apache/kafka/image/S3StreamsMetadataDelta.java
- metadata/src/test/java/org/apache/kafka/image/S3StreamsMetadataImageTest.java
cherry-pick https://github.com/AutoMQ/automq/pull/2041
> fix(metadata): fix stream endoffset set back

- core/src/main/scala/kafka/log/streamaspect/ElasticLog.scala
The same as https://github.com/AutoMQ/automq/pull/2039
> fix(issues2038): fix timestamp to offset not found (#2039)

- raft/src/main/java/org/apache/kafka/raft/QuorumState.java
cherry-pick https://github.com/apache/kafka/pull/17363
> feat(cherry-pick): KAFKA-16927 Handle expanding leader endpoints (#17363)

- automq-shell/src/main/java/com/automq/shell/commands/cluster/Deploy.java
> fix(scripts): start controller node in daemon mode

- automq-shell/src/main/java/com/automq/shell/commands/cluster/Deploy.java
> fix(scripts): fix typo

- automq-shell/src/main/java/com/automq/shell/commands/cluster/Deploy.java
> fix(scripts): add single quotes around the env values

- connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/AutoMQIdentityReplicationPolicy.java
> chore: remove log and add topic check method

- core/src/main/scala/kafka/server/metadata/KRaftMetadataCache.scala
fix #2087
wait for discuss and run in test env.
> fix(metadata): try to fix MetadataImage refCount

- CONTRIBUTING_GUIDE.md
Fix typo and grammar in contributing guide
> docs: Enhance Contributing Guide

- clients/src/main/java/org/apache/kafka/common/network/SaslChannelBuilder.java
> fix(sasl): fix sasl configs

- s3stream/src/main/java/com/automq/stream/s3/compact/CompactionManager.java
> fix(issue2108): avoid blocking at the end of a compaction iteration when there are un-uploaded data

- s3stream/src/main/java/com/automq/stream/s3/compact/CompactionManager.java
cherry-pick https://github.com/AutoMQ/automq/pull/2112
> fix(s3stream): wait force upload complete before return

- core/src/main/scala/kafka/log/stream/s3/DefaultS3Client.java
> revert(s3stream/limiter): increase the max tokens of network limiters

- core/src/main/scala/kafka/log/streamaspect/ElasticUnifiedLog.scala
> perf(log): avoid too many checkpoint at the same time

- tools/src/main/java/org/apache/kafka/tools/automq/perf/ConsumerService.java
- tools/src/main/java/org/apache/kafka/tools/automq/perf/PerfConfig.java
- tools/src/main/java/org/apache/kafka/tools/automq/perf/TopicService.java
> perf(tools/perf): assuming all partitions have the same offset at the same time (#2127)

- s3stream/src/main/java/com/automq/stream/s3/S3Storage.java
> fix(s3stream/storage): correct if condition on `awaitTermination`

- s3stream/src/main/java/com/automq/stream/s3/CompositeObjectReader.java
- s3stream/src/main/java/com/automq/stream/s3/ObjectReader.java
> fix(issue2139): prevent read object info from closed ObjectReader

- s3stream/src/main/java/com/automq/stream/s3/CompositeObjectReader.java
- s3stream/src/main/java/com/automq/stream/s3/ObjectReader.java
- s3stream/src/main/java/com/automq/stream/s3/cache/AsyncLRUCache.java
- s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/DefaultObjectReaderFactory.java
- tools/src/main/java/org/apache/kafka/tools/automq/perf/ConsumerService.java
> fix(issue2139): add computeIfAbsent atomic operation to AsyncLRUCache

- s3stream/src/main/java/com/automq/stream/s3/CompositeObjectReader.java
- s3stream/src/main/java/com/automq/stream/s3/ObjectReader.java
- s3stream/src/main/java/com/automq/stream/s3/cache/AsyncLRUCache.java
> fix(issue2140): remove override equals and hashCode method for ObjectReader

- core/src/main/java/kafka/autobalancer/LoadRetriever.java
- core/src/test/java/kafka/autobalancer/LoadRetrieverTest.java
- s3stream/src/main/java/com/automq/stream/s3/cache/AsyncLRUCache.java
- s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/DefaultObjectReaderFactory.java
> fix(issue2151): avoid using stale broker IPs for AutoBalancer consumer

- .github/CODEOWNERS
> chore(github): update code owners

- build.gradle
- tools/src/main/java/org/apache/kafka/tools/automq/perf/TopicService.java
> feat(tools/perf): create topics in batch

- .github/workflows/build_automq.yml
- s3stream/src/main/java/com/automq/stream/s3/cache/AsyncLRUCache.java
- s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/DefaultObjectReaderFactory.java
- tools/src/main/java/org/apache/kafka/tools/automq/perf/TopicService.java
The same as https://github.com/AutoMQ/automq/pull/2168
> chore(workflow): add spotless check

- s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/StreamReader.java
close https://github.com/AutoMQ/automq/issues/2193
> fix(issues2193): retry 2 times to cover most of BlockNotContinuousException

- docker/docker-compose.yaml
- docker/scripts/start.sh
- override the bucket url in config file
- close https://github.com/AutoMQ/automq/issues/2054
> fix(docker): use bucket url

- docker/docker-compose.yaml
- docker/scripts/start.sh
- adapt to dynamic kraft controller config
> fix(docker): fix docker compose quick start

- gradle/dependencies.gradle
Remove duplicate dependencies.
> build: remove duplicate dependencies

- s3stream/src/main/java/com/automq/stream/utils/CommandUtils.java
cherry-pick https://github.com/AutoMQ/automq/pull/2216
> feat(table): enhance command utils

- tools/src/main/java/org/apache/kafka/tools/automq/PerfCommand.java
fix https://github.com/AutoMQ/automq/issues/2218
> fix(tools/perf): fix the perf tools await count

- s3stream/src/main/java/com/automq/stream/s3/operator/AbstractObjectStorage.java
- s3stream/src/main/java/com/automq/stream/s3/operator/ObjectStorage.java
cherry-pick https://github.com/AutoMQ/automq/pull/2238
> feat(stream): exponential backoff retry

- tools/src/main/java/org/apache/kafka/tools/automq/perf/PerfConfig.java
- tools/src/main/java/org/apache/kafka/tools/automq/perf/ProducerService.java
- tools/src/main/java/org/apache/kafka/tools/automq/perf/TopicService.java
> feat(tools/perf): user experience optimization

- automq-shell/src/main/java/com/automq/shell/commands/cluster/Deploy.java
> fix(cli/deploy): override "controller.quorum.bootstrap.servers"

- automq-shell/src/main/java/com/automq/shell/log/LogRecorder.java
MINOR: fix log4j excetion information
> fix(log4j): fix exception info

- metadata/src/main/java/org/apache/kafka/controller/BrokerHeartbeatManager.java
- metadata/src/main/java/org/apache/kafka/controller/ClusterControlManager.java
- metadata/src/main/java/org/apache/kafka/controller/stream/DefaultNodeRuntimeInfoGetter.java
- metadata/src/main/java/org/apache/kafka/controller/stream/NodeState.java
- metadata/src/test/java/org/apache/kafka/controller/BrokerHeartbeatManagerTest.java
- metadata/src/test/java/org/apache/kafka/controller/stream/NodeControlManagerTest.java
> refactor(controller): consider brokers that has recently `CONTROLLED_SHUTDOWN` as `SHUTTING_DOWN`

- core/src/main/scala/kafka/server/KafkaConfig.scala
Adds the sanity checks proposed in https://github.com/AutoMQ/automq/issues/363
> feat(config): add s3 config validation

- s3stream/src/main/java/com/automq/stream/s3/operator/AwsObjectStorage.java
cherry-pick https://github.com/AutoMQ/automq/pull/2280
> feat(s3stream): fast fail s3 request

- s3stream/src/main/java/com/automq/stream/utils/AsyncSemaphore.java
cherry-pick https://github.com/AutoMQ/automq/pull/2282
> chore(s3stream): replace eventloop with executor in async semaphore

- tools/src/main/java/org/apache/kafka/tools/automq/PerfCommand.java
- tools/src/main/java/org/apache/kafka/tools/automq/perf/TopicService.java
> fix(tools/perf): only delete test topics on reset

- core/src/main/scala/kafka/log/stream/s3/streams/ControllerStreamManager.java
- core/src/main/scala/kafka/log/streamaspect/ClientWrapper.java
- core/src/main/scala/kafka/log/streamaspect/client/memory/ClientFactory.java
- core/src/main/scala/kafka/log/streamaspect/client/s3/ClientFactory.java
cherry-pick https://github.com/AutoMQ/automq/pull/2291
> fix(s3stream): halt the process when node is fenced

- core/src/main/scala/kafka/network/RequestChannel.scala
caused by https://github.com/AutoMQ/automq/pull/2100/commits/28b3ae05be61b5da36e939091d2ab6b8d110b3df
> fix(network): adjust number of permits if the request is huge

- s3stream/src/main/java/com/automq/stream/s3/wal/impl/block/BlockWALService.java
> feat(s3stream/wal): add constraints in recovery mode

- metadata/src/main/java/org/apache/kafka/controller/QuorumController.java
- metadata/src/main/java/org/apache/kafka/controller/stream/StreamControlManager.java
- s3stream/src/main/java/com/automq/stream/s3/failover/Failover.java
- s3stream/src/main/java/com/automq/stream/s3/failover/FailoverRequest.java
- s3stream/src/test/java/com/automq/stream/s3/failover/FailoverTest.java
> feat(s3stream/failover): check request epoch >= wal epoch

- tools/src/main/java/org/apache/kafka/tools/automq/perf/ConsumerService.java
- tools/src/main/java/org/apache/kafka/tools/automq/perf/PerfConfig.java
- tools/src/main/java/org/apache/kafka/tools/automq/perf/ProducerService.java
- tools/src/main/java/org/apache/kafka/tools/automq/perf/TopicService.java
> feat(tool/perf): add option "--common-config-file"

- tools/src/main/java/org/apache/kafka/tools/automq/PerfCommand.java
- tools/src/main/java/org/apache/kafka/tools/automq/perf/ConsumerService.java
> fix(tool/perf): add admin properties in `ConsumerService#admin`

- clients/src/main/java/org/apache/kafka/clients/admin/Admin.java
- clients/src/main/java/org/apache/kafka/clients/admin/ForwardingAdmin.java
- clients/src/main/java/org/apache/kafka/clients/admin/KafkaAdminClient.java
- clients/src/main/java/org/apache/kafka/clients/admin/UpdateGroupOptions.java
- clients/src/main/java/org/apache/kafka/clients/admin/UpdateGroupResult.java
- clients/src/main/java/org/apache/kafka/clients/admin/UpdateGroupSpec.java
- clients/src/main/java/org/apache/kafka/clients/admin/internals/UpdateGroupHandler.java
- clients/src/main/java/org/apache/kafka/common/protocol/ApiKeys.java
- clients/src/main/java/org/apache/kafka/common/requests/AbstractRequest.java
- clients/src/main/java/org/apache/kafka/common/requests/AbstractResponse.java
- clients/src/main/java/org/apache/kafka/common/requests/s3/AutomqUpdateGroupRequest.java
- clients/src/main/java/org/apache/kafka/common/requests/s3/AutomqUpdateGroupResponse.java
- clients/src/main/resources/common/message/AutomqUpdateGroupRequest.json
- clients/src/main/resources/common/message/AutomqUpdateGroupResponse.json
- clients/src/test/java/org/apache/kafka/clients/admin/MockAdminClient.java
- core/src/main/java/kafka/automq/kafkalinking/KafkaLinkingManager.java
- core/src/main/scala/kafka/coordinator/group/GroupCoordinator.scala
- core/src/main/scala/kafka/coordinator/group/GroupCoordinatorAdapter.scala
- core/src/main/scala/kafka/server/BrokerServer.scala
- core/src/main/scala/kafka/server/streamaspect/ElasticKafkaApis.scala
- core/src/main/scala/kafka/server/streamaspect/ElasticReplicaManager.scala
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/GroupCoordinator.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/GroupCoordinatorService.java
- s3stream/src/main/java/com/automq/stream/s3/compact/CompactionManager.java
- add updateGroup interface and api message definition
- support updateGroup in KafkaAdminClient
> feat(linking): add updateGroup interface

- build.gradle
- s3stream/src/main/java/com/automq/stream/s3/DeltaWALUploadTask.java
- s3stream/src/main/java/com/automq/stream/s3/S3Storage.java
- s3stream/src/main/java/com/automq/stream/s3/operator/AbstractObjectStorage.java
- s3stream/src/main/java/com/automq/stream/s3/operator/AwsObjectStorage.java
- s3stream/src/main/java/com/automq/stream/s3/operator/ObjectStorage.java
- s3stream/src/main/java/com/automq/stream/s3/operator/TrafficMonitor.java
- s3stream/src/main/java/com/automq/stream/s3/operator/TrafficRateLimiter.java
- s3stream/src/main/java/com/automq/stream/s3/operator/TrafficRegulator.java
- s3stream/src/main/java/com/automq/stream/s3/operator/TrafficVolumeLimiter.java
> perf(s3stream): limit write traffic to object storage

- s3stream/src/main/java/com/automq/stream/s3/S3Storage.java
> fix(s3storage): release Bytebuf allocated by WAL earlier to prevent memory fragmentation

- core/src/main/scala/kafka/server/ControllerServer.scala
- core/src/main/scala/kafka/server/DynamicBrokerConfig.scala
> refactor(controller): add method `ControllerServer#reconfigurables`

- clients/src/main/java/org/apache/kafka/common/config/TopicConfig.java
- server-common/src/main/java/org/apache/kafka/server/config/ServerTopicConfigSynonyms.java
- storage/src/main/java/org/apache/kafka/storage/internals/log/LogConfig.java
> refactor(core): refine config names for kafka linking (#2348)

- clients/src/main/java/org/apache/kafka/clients/admin/UpdateGroupSpec.java
- clients/src/main/java/org/apache/kafka/clients/admin/internals/UpdateGroupHandler.java
- clients/src/main/resources/common/message/AutomqUpdateGroupRequest.json
> feat(linking): use linkId for update group API

- checkstyle/suppressions.xml
- core/src/main/scala/kafka/log/stream/s3/DefaultS3Client.java
- s3stream/src/main/java/com/automq/stream/s3/DefaultUploadWriteAheadLogTask.java
- s3stream/src/main/java/com/automq/stream/s3/S3Storage.java
- s3stream/src/main/java/com/automq/stream/s3/UploadWriteAheadLogTask.java
- s3stream/src/main/java/com/automq/stream/s3/operator/AbstractObjectStorage.java
- s3stream/src/main/java/com/automq/stream/s3/operator/ObjectStorage.java
- s3stream/src/test/java/com/automq/stream/s3/DeltaWALUploadTaskTest.java
cherry-pick https://github.com/AutoMQ/automq/pull/2356
> feat(s3stream): support s3 write timeout (#2356)

- automq-shell/src/main/java/com/automq/shell/stream/ClientKVClient.java
- core/src/main/java/kafka/autobalancer/goals/AbstractGoal.java
- core/src/main/java/kafka/autobalancer/metricsreporter/AutoBalancerMetricsReporter.java
- core/src/main/java/kafka/autobalancer/metricsreporter/metric/YammerMetricProcessor.java
- core/src/main/scala/kafka/log/LogManager.scala
- core/src/main/scala/kafka/log/stream/s3/ControllerKVClient.java
- core/src/main/scala/kafka/log/streamaspect/ElasticLog.scala
- core/src/main/scala/kafka/log/streamaspect/ElasticLogSegment.java
- core/src/main/scala/kafka/server/AlterPartitionManager.scala
- core/src/main/scala/kafka/server/metadata/KRaftMetadataCache.scala
- core/src/main/scala/kafka/server/streamaspect/BrokerQuotaManager.scala
- s3stream/src/main/java/com/automq/stream/s3/wal/impl/block/SlidingWindowService.java
- storage/src/main/java/org/apache/kafka/storage/internals/log/TimeIndex.java
- tools/src/main/java/org/apache/kafka/tools/automq/perf/TopicService.java
close [#2360](https://github.com/AutoMQ/automq/issues/2360)
> perf: add log level checks to optimize AutoMQ logging performance

- s3stream/src/main/java/com/automq/stream/s3/S3Stream.java
> chore(s3stream): add a space after the log indent

- s3stream/src/main/java/com/automq/stream/s3/exceptions/ObjectNotExistException.java
- s3stream/src/main/java/com/automq/stream/s3/operator/AbstractObjectStorage.java
- s3stream/src/main/java/com/automq/stream/s3/operator/AwsObjectStorage.java
> perf(s3stream/objectstorage): unify the throttle criteria

- s3stream/src/main/java/com/automq/stream/s3/operator/MultiPartWriter.java
Signed-off-by: Shichao Nie <niesc@automq.com>
(cherry picked from commit c330e590734939d8d10b4a3bb0af557edc124400)
> fix(s3stream): skip waiting for pending part on release (#2316)

- automq-shell/src/test/java/com/automq/shell/util/UtilsTest.java
- core/src/test/java/kafka/autobalancer/ControllerActionExecutorServiceTest.java
- core/src/test/java/kafka/autobalancer/goals/GoalTestBase.java
- core/src/test/java/kafka/autobalancer/goals/ResourceUsageDistributionGoalTest.java
- core/src/test/java/kafka/autobalancer/metricsreporter/AutoBalancerMetricsReporterTest.java
- core/src/test/java/kafka/autobalancer/metricsreporter/metric/MetricSerdeTest.java
- core/src/test/java/kafka/autobalancer/metricsreporter/metric/MetricsUtilsTest.java
- core/src/test/java/kafka/autobalancer/model/ClusterModelTest.java
- core/src/test/java/kafka/log/streamaspect/ElasticLogSegmentManagerTest.java
- core/src/test/java/kafka/log/streamaspect/ElasticTimeIndexTest.java
- core/src/test/java/kafka/log/streamaspect/ElasticTransactionIndexTest.java
- core/src/test/java/kafka/log/streamaspect/PartitionStatusTrackerTest.java
- core/src/test/java/kafka/log/streamaspect/cache/FileCacheTest.java
- core/src/test/scala/kafka/log/streamaspect/ElasticLogCleanerTest.scala
- core/src/test/scala/kafka/log/streamaspect/ElasticLogTest.scala
- core/src/test/scala/kafka/log/streamaspect/ElasticProducerStateManagerTest.scala
- core/src/test/scala/kafka/log/streamaspect/ElasticUnifiedLogTest.scala
- core/src/test/scala/unit/kafka/server/BrokerQuotaManagerTest.java
- core/src/test/scala/unit/kafka/server/ControllerConfigurationValidatorTableTest.scala
- core/src/test/scala/unit/kafka/server/streamaspect/ElasticControllerApisTest.scala
- core/src/test/scala/unit/kafka/server/streamaspect/ElasticKafkaApisTest.scala
- core/src/test/scala/unit/kafka/server/streamaspect/ElasticReplicaManagerTest.scala
- metadata/src/test/java/org/apache/kafka/controller/ElasticPartitionChangeBuilderTest.java
- metadata/src/test/java/org/apache/kafka/controller/stream/OverloadCircuitBreakerTest.java
- metadata/src/test/java/org/apache/kafka/controller/stream/StreamRuntimeMetadataTest.java
- metadata/src/test/java/org/apache/kafka/metadata/stream/SortedStreamSetObjectsListTest.java
cherry-pick https://github.com/AutoMQ/automq/pull/2410
> chore(test): add test timeout

- automq_release.py
- s3stream/pom.xml
- s3stream/src/main/java/com/automq/stream/s3/operator/TrafficVolumeLimiter.java
fix a dependency error in s3stream
> fix: fix a dependency error

- s3stream/src/main/java/com/automq/stream/s3/wal/impl/block/BlockWALService.java
- s3stream/src/main/java/com/automq/stream/s3/wal/util/AbstractWALChannel.java
- s3stream/src/main/java/com/automq/stream/s3/wal/util/WALCachedChannel.java
- s3stream/src/main/java/com/automq/stream/s3/wal/util/WALChannel.java
> perf(s3stream/wal): add append timeout in block WAL

- core/src/main/java/kafka/autobalancer/LoadRetriever.java
- core/src/main/scala/kafka/log/stream/s3/metadata/StreamMetadataManager.java
- core/src/main/scala/kafka/log/stream/s3/network/ControllerRequestSender.java
- core/src/main/scala/kafka/log/streamaspect/ElasticUnifiedLog.scala
- s3stream/src/main/java/com/automq/stream/s3/index/LocalStreamRangeIndexCache.java
- s3stream/src/main/java/com/automq/stream/s3/network/AsyncNetworkBandwidthLimiter.java
- s3stream/src/main/java/com/automq/stream/utils/threads/S3StreamThreadPoolMonitor.java
- tools/src/main/java/org/apache/kafka/tools/automq/perf/ProducerService.java
This pull request attempts to resolve https://github.com/AutoMQ/automq/issues/2357 .
> perf: Replace Unsafe ScheduledExecutorService Initialization with Exception-Handling Wrapper

- s3stream/src/main/java/com/automq/stream/s3/operator/LocalFileObjectStorage.java
- s3stream/src/test/java/com/automq/stream/s3/operator/LocalFileObjectStorageTest.java
cherry-pick https://github.com/AutoMQ/automq/pull/2415
> feat(circuit): add LocalFileObjectStorage storage limit (#2415)

- metadata/src/main/java/org/apache/kafka/controller/stream/NodeControlManager.java
cherry-pick https://github.com/AutoMQ/automq/pull/2418
> feat(circuit): prevent unregister locked node (#2418)

- core/src/main/java/kafka/automq/interceptor/ClientIdMetadata.java
cherry-pick https://github.com/AutoMQ/automq/pull/2421
> feat(interceptor): extend client id

- s3stream/src/main/java/com/automq/stream/s3/index/LocalStreamRangeIndexCache.java
- s3stream/src/test/java/com/automq/stream/s3/index/LocalStreamRangeIndexCacheTest.java
> fix(s3stream): fix potential index leak on stream deletion

- core/src/main/scala/kafka/server/BrokerServer.scala
- core/src/main/scala/kafka/server/KafkaApis.scala
- core/src/main/scala/kafka/server/streamaspect/ElasticKafkaApis.scala
- core/src/main/scala/kafka/server/streamaspect/ElasticReplicaManager.scala
cherry-pick https://github.com/AutoMQ/automq/pull/2436
> feat(snapshot_read): support preferred node (#2436)

- build.gradle
cherry-pick https://github.com/AutoMQ/automq/pull/2445
> fix(gradle): fix kafka-client conflict #2445

- s3stream/src/main/java/com/automq/stream/s3/cache/SnapshotReadCache.java
cherry-pick https://github.com/AutoMQ/automq/pull/2460
> fix(snapshot_read): fix snapshot-read cache tryload trigger

- README.md
> chore: update README.md and make it more developer readable

- .github/ISSUE_TEMPLATE/bug-report.md
> chore: improve the bug-report template

- .github/ISSUE_TEMPLATE/good-first-issue.md
> chore: improve the good-first-issue template

- README.md
> chore: improve the why-automq chapter of README.md

- .editorconfig
- README.md
- docker/docker-compose.yaml
> chore: provide a more practical quick start for single node setup

- docker/README.md
- docker/docker-compose-cluster.yaml
> chore: provide a more practical quick start for three nodes setup

- .github/workflows/auto-assign-issue.yml
added the feature to auto assign the issue to anyone who comments "/assign"
with reference to "Introduce a bot or action to automatically assign issues #2486"
> chore: Create auto-assign-issue.yml

- CONTRIBUTING_GUIDE.md
> chore: Update CONTRIBUTING_GUIDE.md to indicate support for automatic issue assignment

- automq-shell/src/main/resources/template/topo.yaml
- s3stream/src/main/java/com/automq/stream/s3/operator/AutoMQStaticCredentialsProvider.java
- s3stream/src/main/java/com/automq/stream/s3/operator/AwsObjectStorage.java
- s3stream/src/test/java/com/automq/stream/s3/operator/AwsObjectStorageTest.java
> fix(s3stream): fix backward compatibility of default aws credentials

- build.gradle
- core/src/main/java/kafka/automq/table/CatalogFactory.java
- tests/kafkatest/services/kafka/templates/kafka.properties
cherry-pick https://github.com/AutoMQ/automq/pull/2518
> fix(test): fix e2e dependencies conflict (#2518)

- s3stream/src/test/java/com/automq/stream/s3/S3StorageTest.java
This PR adds comprehensive unit tests for the `WALConfirmOffsetCalculator` class in the `com.automq.stream.s3` package. This class is a key component in the WAL trimming process, used to determine the offset up to which data can be safely discarded from WAL.
Previously, this class had no direct test coverage, making its correctness reliant on indirect tests or production behavior. The new tests validate the core behavior of the `calculate()` method, which scans a queue of `WalWriteRequest`s to determine the highest confirmed offset.
These tests improve confidence in the correctness of offset calculation logic under different confirmation scenarios, including:
* All requests confirmed
* Some unconfirmed (blocking confirmation)
* All unconfirmed
* Empty queue
---
This change includes a new …
> test(s3stream): Add unit tests for WALConfirmOffsetCalculator (#2367)

- build.gradle
- core/src/main/java/kafka/automq/table/utils/PartitionUtil.java
- core/src/main/java/kafka/automq/table/worker/WorkerConfig.java
- core/src/test/java/kafka/automq/table/utils/PartitionUtilTest.java
- server-common/src/main/java/org/apache/kafka/server/common/automq/TableTopicConfigValidator.java
- server-common/src/test/java/org/apache/kafka/server/common/automq/TableTopicConfigValidatorTest.java
- storage/src/main/java/org/apache/kafka/storage/internals/log/LogConfig.java
cherry-pick https://github.com/AutoMQ/automq/pull/2522
> feat(table): validate table config

- s3stream/src/main/java/com/automq/stream/s3/S3Storage.java
cherry-pick https://github.com/AutoMQ/automq/pull/2526
> fix(storage): fix upload wal rate missing

- s3stream/src/main/java/com/automq/stream/s3/wal/impl/object/RecordAccumulator.java
> fix(s3stream): add delayed deletion for S3 WAL

- s3stream/src/main/java/com/automq/stream/s3/S3Storage.java
cherry-pick https://github.com/AutoMQ/automq/pull/2533
> feat(zerozone): fast upload when snapshot-read enable

- s3stream/src/main/java/com/automq/stream/s3/wal/impl/object/ObjectWALService.java
- s3stream/src/main/java/com/automq/stream/s3/wal/impl/object/RecordAccumulator.java
- s3stream/src/main/java/com/automq/stream/s3/wal/impl/object/WALObjectHeader.java
- s3stream/src/test/java/com/automq/stream/s3/wal/impl/object/MockObjectStorage.java
- s3stream/src/test/java/com/automq/stream/s3/wal/impl/object/ObjectWALServiceTest.java
- s3stream/src/test/java/com/automq/stream/s3/wal/impl/object/RecordAccumulatorTest.java
- s3stream/src/test/java/com/automq/stream/s3/wal/impl/object/WALObjectHeaderTest.java
> refactor(s3stream/object-wal): complete appends sequentially

- .github/workflows/spark-iceberg-docker-build.yml
> fix(workflow): update Docker image tag for Spark Iceberg build

- README.md
Add star module for AutoMQ README.
> fix(README): add star automq module

- .github/workflows/spark-iceberg-docker-build.yml
- docker/table_topic/README.md
- docker/table_topic/docker-compose.yml
- docker/table_topic/spark_iceberg/Dockerfile
- docker/table_topic/spark_iceberg/notebooks/TableTopic - Getting Started.ipynb
> feat(docker): add Spark Iceberg Docker setup and demonstration notebook

- container/bitnami/Dockerfile
- container/bitnami/docker-compose.yml
- container/bitnami/prebuildfs/opt/bitnami/.bitnami_components.json
- container/bitnami/prebuildfs/opt/bitnami/licenses/licenses.txt
- container/bitnami/prebuildfs/opt/bitnami/scripts/libbitnami.sh
- container/bitnami/prebuildfs/opt/bitnami/scripts/libfile.sh
- container/bitnami/prebuildfs/opt/bitnami/scripts/libfs.sh
- container/bitnami/prebuildfs/opt/bitnami/scripts/libhook.sh
- container/bitnami/prebuildfs/opt/bitnami/scripts/liblog.sh
- container/bitnami/prebuildfs/opt/bitnami/scripts/libnet.sh
- container/bitnami/prebuildfs/opt/bitnami/scripts/libos.sh
- container/bitnami/prebuildfs/opt/bitnami/scripts/libpersistence.sh
- container/bitnami/prebuildfs/opt/bitnami/scripts/libservice.sh
- container/bitnami/prebuildfs/opt/bitnami/scripts/libvalidations.sh
- container/bitnami/prebuildfs/opt/bitnami/scripts/libversion.sh
- container/bitnami/prebuildfs/opt/bitnami/scripts/libwebserver.sh
- container/bitnami/prebuildfs/usr/sbin/install_packages
- container/bitnami/prebuildfs/usr/sbin/run-script
- container/bitnami/rootfs/opt/bitnami/scripts/java/entrypoint.sh
- container/bitnami/rootfs/opt/bitnami/scripts/java/postunpack.sh
- container/bitnami/rootfs/opt/bitnami/scripts/kafka-env.sh
- container/bitnami/rootfs/opt/bitnami/scripts/kafka/entrypoint.sh
- container/bitnami/rootfs/opt/bitnami/scripts/kafka/postunpack.sh
- container/bitnami/rootfs/opt/bitnami/scripts/kafka/run.sh
- container/bitnami/rootfs/opt/bitnami/scripts/kafka/setup.sh
- container/bitnami/rootfs/opt/bitnami/scripts/libkafka.sh
- container/bitnami/tags-info.yaml
* feat(bitnami): init and cp bitnami kafka container 3.9.0
* refactor(bitnami): rename Bitnami container files for consistency
#2560 
> feat: cherry-pick 2560

- .github/workflows/docker-bitnami-release.yaml
- chart/bitnami/README.md
- chart/bitnami/demo-values.yaml
- container/automq_chart_feature.patch
- container/bitnami/Dockerfile
- container/bitnami/rootfs/opt/bitnami/scripts/kafka/postunpack.sh
The same as: #2561 #2570 #2562 #2574
> feat(container): cp_2561_2570_2562_2574

- docker/README.md
- docker/docker-compose-cluster.yaml
cherry-pick https://github.com/AutoMQ/automq/pull/2468 https://github.com/AutoMQ/automq/pull/2469
> feat(docker): cherry pick #2468 #2469

- tools/src/main/java/org/apache/kafka/tools/automq/perf/ConsumerService.java
- tools/src/main/java/org/apache/kafka/tools/automq/perf/ProducerService.java
> perf(tool/perf): reduce the record header size

- core/src/main/java/kafka/automq/table/CredentialProviderHolder.java
- core/src/main/java/kafka/automq/zerozone/RouterIn.java
- core/src/main/java/kafka/automq/zerozone/RouterInProduceHandler.java
- core/src/main/java/kafka/automq/zerozone/ZeroZoneTrafficInterceptor.java
- core/src/main/scala/kafka/server/BrokerServer.scala
cherry-pick https://github.com/AutoMQ/automq/pull/2582
> chore(all): make code more extendable (#2582)

- chart/bitnami/demo-values.yaml
> chore(chart): update demo-values.yaml to correct AWS environment variable names

- s3stream/src/main/java/com/automq/stream/s3/S3Storage.java
- s3stream/src/main/java/com/automq/stream/utils/ExceptionUtil.java
> refactor(s3stream): in preparation for segmented recovery (#2589)

- s3stream/src/main/java/com/automq/stream/s3/S3Storage.java
This is a fully equivalent reconstruction.
> refactor(s3stream): preparation for segmented recovery

- core/src/main/scala/kafka/log/stream/s3/node/NodeManager.java
- core/src/main/scala/kafka/log/stream/s3/node/NodeManagerStub.java
- metadata/src/main/java/org/apache/kafka/controller/stream/NodeMetadata.java
cherry-pick https://github.com/AutoMQ/automq/pull/2594
> fix(s3stream): fix node epoch outdated

- s3stream/src/main/java/com/automq/stream/s3/S3Storage.java
- s3stream/src/main/java/com/automq/stream/s3/cache/LogCache.java
- s3stream/src/test/java/com/automq/stream/s3/S3StorageTest.java
> perf(s3stream): recover and upload data in segments

- core/src/main/scala/kafka/log/stream/s3/DefaultS3Client.java
> fix(s3client): limit the network usage of object storages

- build.gradle
- gradle/dependencies.gradle
- tools/src/main/java/org/apache/kafka/tools/automq/perf/CpuMonitor.java
- tools/src/main/java/org/apache/kafka/tools/automq/perf/MemoryMonitor.java
- tools/src/main/java/org/apache/kafka/tools/automq/perf/PerfConfig.java
- tools/src/main/java/org/apache/kafka/tools/automq/perf/StatsCollector.java
Cherry pick following PRs:
- #2606 
- #2607
- #2608
> feat(tools/perf): log cpu, memory usage and min latency

- streams/src/test/java/org/apache/kafka/streams/tests/RelationalSmokeTest.java
- tests/kafkatest/automq/compaction_test.py
- tests/kafkatest/automq/memory_occupancy_test.py
- tests/kafkatest/automq/quota_test.py
- tests/kafkatest/automq/s3_leakage_test.py
- tests/kafkatest/benchmarks/core/benchmark_test.py
- tests/kafkatest/sanity_checks/test_performance_services.py
- tests/kafkatest/services/log_compaction_tester.py
- tests/kafkatest/tests/connect/connect_distributed_test.py
- tests/kafkatest/tests/core/group_mode_transactions_test.py
- tests/kafkatest/tests/core/reassign_partitions_test.py
- tests/kafkatest/tests/core/replica_scale_test.py
- tests/kafkatest/tests/core/round_trip_fault_test.py
- tests/kafkatest/tests/core/snapshot_test.py
- tests/kafkatest/tests/core/transactions_test.py
- tests/kafkatest/tests/produce_consume_validate.py
- tests/kafkatest/tests/streams/base_streams_test.py
- tests/kafkatest/tests/streams/streams_broker_down_resilience_test.py
- tests/kafkatest/tests/streams/streams_relational_smoke_test.py
- tests/kafkatest/tests/streams/streams_standby_replica_test.py
> fix(e2e): fix e2e test

- tests/kafkatest/tests/client/consumer_test.py
This small PR fixes the syntax issue and cleanups the duplicated parameters.
> fix: clean up duplicated parameters

- docker/docker-compose-cluster.yaml
- docker/docker-compose.yaml
- docker/table_topic/docker-compose.yml
https://github.com/minio/mc/issues/5206
> fix(docker): update MinIO command from config host to alias set

- .github/workflows/e2e-run.yml
add retry for flaky e2e tests.
> fix(e2e): add retry for flaky tests

- build.gradle
> fix(e2e): fix stream update test

- README.md
> feat(README): add customer wall logos

- build.gradle
cherry-pick https://github.com/AutoMQ/automq/pull/2637
> feat(tabletopic): default include hive catalog dependencies

- config/perf-log4j.properties
> chore(tools/perf): log client logs to a separate file

- core/src/main/scala/kafka/log/stream/s3/metadata/StreamMetadataManager.java
- metadata/src/main/java/org/apache/kafka/image/S3StreamsMetadataImage.java
cherry-pick https://github.com/AutoMQ/automq/pull/2653
> fix(image): guard streams image access with lock to prevent data loss (#2653)

- core/src/main/scala/kafka/log/stream/s3/metadata/StreamMetadataManager.java
> fix(s3stream): avoid StreamMetadataManager add callback when retry

- container/automq_chart_feature.patch
- container/bitnami/prebuildfs/opt/bitnami/scripts/libbitnami.sh
> chore(container): update welcome message and container patch (#2658)

- core/src/main/scala/kafka/server/FairLimiter.java
cherry-pick https://github.com/AutoMQ/automq/pull/2670
> perf(misc): optimize FairLimiter implementation (#2670)

- s3stream/src/main/java/com/automq/stream/s3/wal/benchmark/RecoverTool.java
- s3stream/src/main/java/com/automq/stream/s3/wal/common/RecordHeader.java
- s3stream/src/main/java/com/automq/stream/s3/wal/impl/block/Block.java
- s3stream/src/main/java/com/automq/stream/s3/wal/impl/block/BlockImpl.java
- s3stream/src/main/java/com/automq/stream/s3/wal/impl/block/BlockWALHeader.java
- s3stream/src/main/java/com/automq/stream/s3/wal/impl/block/BlockWALService.java
- s3stream/src/main/java/com/automq/stream/s3/wal/impl/block/SlidingWindowService.java
- s3stream/src/main/java/com/automq/stream/s3/wal/impl/object/ObjectWALService.java
- s3stream/src/main/java/com/automq/stream/s3/wal/util/WALUtil.java
- s3stream/src/test/java/com/automq/stream/s3/wal/impl/block/BlockWALHeaderTest.java
- s3stream/src/test/java/com/automq/stream/s3/wal/impl/block/BlockWALServiceTest.java
- s3stream/src/test/java/com/automq/stream/s3/wal/impl/object/ObjectWALServiceTest.java
Cherry-pick PRs:
- #2665 
- #2673 
- #2676
> feat(block-wal): use version V1 and support sequential return

- core/src/main/java/kafka/automq/table/worker/TopicPartitionsWorker.java
- core/src/test/java/kafka/automq/table/worker/TopicPartitionsWorkerTest.java
https://github.com/AutoMQ/automq/issues/2669
> fix(worker): update CommitResponse to use partition type from writerFactory

- README.md
> fix(README): readme-logo

- .github/CODEOWNERS
cherry-pick https://github.com/AutoMQ/automq/pull/2695
> chore(github): change code owners

- core/src/main/scala/kafka/log/LogCleaner.scala
cherry-pick 80b9377da3e5cca81f6eb16617fd229287fc94df
> fix(logCleaner): optimize write buffer management and clear buffer before use (#2704)

- build.gradle
- core/src/main/scala/kafka/log/streamaspect/ElasticLogFileRecords.java
- core/src/main/scala/kafka/log/streamaspect/MemoryClient.java
- core/src/test/java/kafka/log/streamaspect/ElasticLogFileRecordsTest.java
> feat(log): enhance reading logic to handle offset gaps and add unit tests

- core/src/main/scala/kafka/log/streamaspect/ElasticLogFileRecords.java
cherry-pick 06eef9ae7845e2436d2b2f84884e2382018952c7
https://github.com/AutoMQ/automq/issues/2715
> perf(log): increase FETCH_BATCH_SIZE to 512KB in StreamSegmentInputStream (#2722)

- bin/kafka-run-class.sh
- build.gradle
add releaseE2ETar build task for enterprise e2e running environment.
remove exclude test-sources jar and connect-file.jar for running e2e in enterprise need.
> feat: modify for enterprise e2e

- automq-shell/src/main/java/com/automq/shell/commands/cluster/Deploy.java
cherry-pick https://github.com/AutoMQ/automq/pull/2747
> fix: Added support for AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY

- bin/kafka-run-class.sh
- build.gradle
remove unnecessary import to fix e2e.
> fix(e2e): fix benchmark e2e

- build.gradle
cherry-picked from #2754
remove unnecessary imports to fix e2e.
> fix(e2e): cherry pick to fix e2e

- core/src/main/scala/kafka/log/stream/s3/DefaultS3Client.java
cherry-pick https://github.com/AutoMQ/automq/pull/2759
> fix(failover): fix failover get wrong node config

- s3stream/src/main/java/com/automq/stream/s3/metrics/stats/AsyncLRUCacheStats.java
- s3stream/src/main/java/com/automq/stream/s3/metrics/stats/S3OperationStats.java
Fix lock object error when implementing singleton pattern.
> fix(core): fix lock object error when implementing singleton pattern

- s3stream/src/main/java/com/automq/stream/s3/wal/impl/object/DefaultWriter.java
- s3stream/src/main/java/com/automq/stream/s3/wal/impl/object/ObjectWALService.java
cherry-pick https://github.com/AutoMQ/automq/pull/2780
> fix(zerozone2): fix failover bug caused by #2764

- core/src/main/java/kafka/automq/zerozone/DefaultRouterChannelProvider.java
- core/src/main/java/kafka/automq/zerozone/ObjectRouterChannel.java
- core/src/main/java/kafka/automq/zerozone/RouterChannel.java
- core/src/main/java/kafka/automq/zerozone/RouterChannelProvider.java
- core/src/main/java/kafka/automq/zerozone/SnapshotReadPartitionsManager.java
- core/src/main/java/kafka/automq/zerozone/SubscriberReplayer.java
- core/src/main/java/kafka/automq/zerozone/ZeroZoneTrafficInterceptor.java
- core/src/main/scala/kafka/server/BrokerServer.scala
- core/src/test/java/kafka/automq/zerozone/SnapshotReadPartitionsManagerTest.java
cherry-pick https://github.com/AutoMQ/automq/pull/2787
> refactor(zerozone2): make wal provider more extensible (#2787)

- core/src/main/java/kafka/automq/zerozone/RouterInV2.java
- core/src/main/java/kafka/automq/zerozone/ZeroZoneTrafficInterceptor.java
cherry-pick https://github.com/AutoMQ/automq/pull/2789
> feat(zerozone2): force route to local

- core/src/main/java/kafka/automq/zerozone/ChannelOffset.java
cherry-pick https://github.com/AutoMQ/automq/pull/2793
> chore(zerozone2): rename channelOffset targetNodeId to attributes

- README.md
> feat(README): Add promotional images to the Readme

- README.md
> feat(README): Update README.md use new solgan

- build.gradle
- s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/StreamReaders.java
- s3stream/src/main/java/com/automq/stream/s3/exceptions/ObjectNotExistException.java
- s3stream/src/main/java/com/automq/stream/s3/metrics/Metrics.java
cherry-pick https://github.com/AutoMQ/automq/pull/2803
> feat(java): set min java version to 17

- s3stream/src/main/java/com/automq/stream/s3/wal/impl/object/DefaultWriter.java
- s3stream/src/test/java/com/automq/stream/s3/wal/impl/object/ObjectWALServiceTest.java
The reset shouldn't trim to the nextOffset. It may cause the next write record to be trimmed by mistake.
> fix(zerozone2): fix potential WAL reset overflow BUG

- s3stream/src/main/java/com/automq/stream/s3/wal/impl/object/DefaultWriter.java
- s3stream/src/main/java/com/automq/stream/s3/wal/impl/object/ObjectWALConfig.java
cherry-pick https://github.com/AutoMQ/automq/pull/2809
> perf(zerozone2): optimize the wal batch upload strategy

- .github/workflows/publish_maven_package.yml
cherry-pick https://github.com/AutoMQ/automq/pull/2812
> chore(workflows): add publish maven package workflow

- core/src/main/scala/kafka/server/streamaspect/ElasticReplicaManager.scala
- metadata/src/main/java/org/apache/kafka/controller/ReplicationControlManager.java
cherry-pick https://github.com/AutoMQ/automq/pull/2821
> feat(reassign): optimize partition reassignment to avoid client fast retry

- .github/workflows/docker-kafka-release.yaml
- docker/automq-feat-kafka-docker.patch
- docker/jvm/Dockerfile
- docker/jvm/launch
- Adapted Kafka Docker image build process for improved compatibility with main branch
- Optimized build scripts and dependency management to simplify image creation
- Fixed environment variable and configuration compatibility issues within containers
- Added/updated related documentation and usage examples
- Kafka Docker image build workflow and related scripts
- Docker deployment documentation
- Dependency configuration and environment adaptation
Please pay special attention to changes in Dockerfile, build scripts, and related configurations to ensure image usability across different environments.
---
If there are additional specific changes or test instructions, please add them in the PR comments.
> feat(docker): kafka docker image adapt

- server-common/src/main/java/org/apache/kafka/server/common/automq/TableTopicConfigValidator.java
- server-common/src/test/java/org/apache/kafka/server/common/automq/TableTopicConfigValidatorTest.java
cherry-pick https://github.com/AutoMQ/automq/commit/1bcc9c76435c80de96838c3eb45cc025ec102c92 https://github.com/AutoMQ/automq/pull/2836
> fix(config): remove exception for invalid list string in TableTopicConfigValidator (#2836)

- s3stream/src/main/java/com/automq/stream/s3/S3Storage.java
- s3stream/src/main/java/com/automq/stream/s3/wal/impl/object/ObjectWALConfig.java
- s3stream/src/main/java/com/automq/stream/s3/wal/impl/object/ObjectWALService.java
cherry-pick https://github.com/AutoMQ/automq/pull/2841
> fix(s3stream): fix buf leak when recover fail

- core/src/main/scala/kafka/log/streamaspect/ElasticUnifiedLog.scala
cherry-pick https://github.com/AutoMQ/automq/pull/2848
> fix(log): fix potential fetch NPE when the partition is closing

- s3stream/src/main/java/com/automq/stream/s3/metrics/wrapper/DeltaHistogram.java
fix(metrics): fix percentile metrics
> fix(metrics): fix percentile metrics

- s3stream/src/main/java/com/automq/stream/s3/metrics/wrapper/DeltaHistogram.java
fix(metrics): fix percentile metrics (#2849)
> fix(metrics): fix percentile metrics (#2849)

- s3stream/src/main/java/com/automq/stream/s3/metrics/wrapper/DeltaHistogram.java
feat(metrics): enhance metrics for benchmark (#2856)
> feat(metrics): enhance metrics for benchmark (#2856)

- core/src/main/java/kafka/automq/zerozone/SnapshotReadPartitionsManager.java
- metadata/src/main/java/org/apache/kafka/controller/QuorumController.java
cherry-pick https://github.com/AutoMQ/automq/pull/2858
> fix(zerozone2): await subscriber close

- s3stream/src/main/java/com/automq/stream/s3/metrics/wrapper/DeltaHistogram.java
feat(metrics): enhance metrics for benchmark, control the interval time based on the snapshot generation time point
> feat(metrics): enhance metrics for benchmark

- s3stream/src/main/java/com/automq/stream/s3/metrics/wrapper/DeltaHistogram.java
feat(metrics): enhance metrics for benchmark, control the interval time based on the snapshot generation time point
> feat(metrics): enhance metrics for benchmark (#2860)

- core/src/main/java/kafka/automq/table/binder/AvroValueAdapter.java
- core/src/main/java/kafka/automq/table/binder/RecordBinder.java
- core/src/main/java/kafka/automq/table/metric/FieldMetric.java
- core/src/main/java/kafka/automq/table/process/DefaultRecordProcessor.java
- core/src/main/java/kafka/automq/table/process/RecordAssembler.java
- core/src/main/java/kafka/automq/table/process/convert/RawConverter.java
- core/src/main/java/kafka/automq/table/process/convert/StringConverter.java
- core/src/main/java/kafka/automq/table/process/transform/DebeziumUnwrapTransform.java
- core/src/test/java/kafka/automq/table/binder/AvroRecordBinderTest.java
- core/src/test/java/kafka/automq/table/process/DefaultRecordProcessorTest.java
- core/src/test/java/kafka/automq/table/process/RecordAssemblerTest.java
cherry-pick: https://github.com/AutoMQ/automq/commit/3421ad26cac6ef3305775064da6692f8b67d76b2 (#2855)
> feat: enhance schema handling and optimize record processing (#2855)

- s3stream/src/main/java/com/automq/stream/s3/metrics/Metrics.java
- s3stream/src/main/java/com/automq/stream/s3/metrics/wrapper/DeltaHistogram.java
- s3stream/src/main/java/com/automq/stream/s3/metrics/wrapper/HistogramMetric.java
cherry-pick https://github.com/AutoMQ/automq/pull/2868
> fix(metrics): set the interval for the lazy-created histogram

- s3stream/src/main/java/com/automq/stream/s3/wal/impl/object/DefaultWriter.java
cherry-pick https://github.com/AutoMQ/automq/pull/2888
> fix(wal): try drain all waiting upload bulks

- core/src/test/java/kafka/automq/table/process/convert/ProtobufRegistryConverterTest.java
[feat(tests): add Protobuf ConverterTest for comprehensive Protobuf conversion validation](https://github.com/AutoMQ/automq/commit/d3a3847fd0d556ff1f7143285441827c2a1b679a)
cherry-pick: https://github.com/AutoMQ/automq/pull/2885
> feat(tests): add Protobuf ConverterTest for comprehensive Protobuf conversion validation (#2885)

- core/src/main/scala/kafka/cluster/Partition.scala
- core/src/main/scala/kafka/log/streamaspect/ElasticUnifiedLog.scala
cherry-pick https://github.com/AutoMQ/automq/pull/2907
> fix(zerozone2): guard snapshot by lock

- s3stream/src/main/java/com/automq/stream/s3/S3Stream.java
cherry-pick https://github.com/AutoMQ/automq/pull/2909
> chore(zerozone2): clean up s3stream metrics

- core/src/main/java/kafka/automq/partition/snapshot/PartitionSnapshotsManager.java
- core/src/main/scala/kafka/cluster/Partition.scala
cherry-pick https://github.com/AutoMQ/automq/pull/2911
> fix(zerozone2): fix epoch missing update when there isn't new record

- core/src/main/java/kafka/automq/table/CatalogFactory.java
- core/src/test/java/kafka/automq/table/CatalogFactoryTest.java
cherry-pick: https://github.com/AutoMQ/automq/pull/2915 https://github.com/AutoMQ/automq/pull/2892
> fix: ensure S3 endpoint is not required for table topic since AWS client can guess it most of the time (#2915)

- core/src/main/java/kafka/automq/partition/snapshot/PartitionSnapshotsManager.java
- core/src/main/java/kafka/cluster/PartitionSnapshot.java
- core/src/main/scala/kafka/cluster/Partition.scala
- core/src/main/scala/kafka/log/streamaspect/ClientWrapper.java
- core/src/main/scala/kafka/log/streamaspect/ElasticLog.scala
- core/src/main/scala/kafka/log/streamaspect/LazyStream.java
- core/src/main/scala/kafka/log/streamaspect/MemoryClient.java
- core/src/main/scala/kafka/log/streamaspect/MetaStream.java
- core/src/test/java/kafka/automq/zerozone/SnapshotReadPartitionsManagerTest.java
- s3stream/src/main/java/com/automq/stream/api/Stream.java
- s3stream/src/main/java/com/automq/stream/s3/S3Stream.java
- s3stream/src/main/java/com/automq/stream/s3/S3StreamClient.java
cherry-pick https://github.com/AutoMQ/automq/pull/2920
> fix(zerozone2): fix the snapshot to avoid consuming abort txn record

- core/src/main/java/kafka/cluster/LogEventListener.java
- core/src/main/scala/kafka/log/streamaspect/ElasticLog.scala
- core/src/main/scala/kafka/log/streamaspect/ElasticLogSegmentManager.java
- core/src/main/scala/kafka/log/streamaspect/ElasticLogStreamManager.java
- Update the snapshot version when the lazy stream has been created. 
- Replace the NOOP stream when lazy stream has been created.
> fix(zerozone2): support lazy stream
