core/src/main/scala/kafka/log/ProducerStateManager.scala
close https://github.com/AutoMQ/automq-for-kafka/issues/437
=> fix: issue437, producer snapshot cannot detect duplicated

core/src/main/scala/kafka/log/LocalLog.scala, core/src/main/scala/kafka/log/streamaspect/ElasticLog.scala, core/src/main/scala/kafka/log/streamaspect/ElasticLogFileRecords.java, core/src/main/scala/kafka/log/streamaspect/ReadAllHint.java, core/src/main/scala/kafka/server/DelayedFetch.scala, core/src/main/scala/kafka/server/KafkaApis.scala
close https://github.com/AutoMQ/automq-for-kafka/issues/440
=> fix(issue440): get lastOffst from records

core/src/main/scala/kafka/server/ReplicaManager.scala
close https://github.com/AutoMQ/automq-for-kafka/issues/460
=> fix(isssue460): fix read result concurrent modify

connect/json/src/main/java/org/apache/kafka/connect/json/JsonConverter.java, connect/json/src/main/java/org/apache/kafka/connect/json/JsonDeserializer.java, connect/json/src/main/java/org/apache/kafka/connect/json/JsonSerializer.java, connect/json/src/test/java/org/apache/kafka/connect/json/JsonConverterTest.java, gradle/dependencies.gradle
https://github.com/AutoMQ/automq-for-kafka/issues/469
=> fix(e2e): unify jackson to 2.16.0

core/src/main/scala/kafka/server/KafkaApis.scala, core/src/main/scala/kafka/server/MemoryLimiter.java, core/src/main/scala/kafka/server/ReplicaManager.scala
close https://github.com/AutoMQ/automq-for-kafka/issues/487
=> feat(issues487): add fetch memory static 200MB limiter

core/src/main/scala/kafka/server/KafkaConfig.scala, core/src/main/scala/kafka/server/ReplicaManager.scala, docker/scripts/start.sh
close https://github.com/AutoMQ/automq-for-kafka/issues/490
=> feat(issuse490): check fetch await time

core/src/main/scala/kafka/log/stream/s3/streams/ControllerStreamManager.java, core/src/main/scala/kafka/log/streamaspect/ElasticLog.scala, core/src/main/scala/kafka/log/streamaspect/ElasticLogSegment.scala, core/src/test/scala/unit/kafka/log/streamaspect/ElasticLogSegmentTest.scala, core/src/test/scala/unit/kafka/log/streamaspect/ElasticLogTest.scala, core/src/test/scala/unit/kafka/log/streamaspect/ElasticUnifiedLogTest.scala
In this pull request, to prevent reading the initial batch in ElasticLogSegment#timeWaitedForRoll, the createTimeStamp in ElasticStreamSegmentMeta is utilized to denote the initial timestamp.
=> fix(core): avoid reading when checking shouldRoll

core/src/main/scala/kafka/log/streamaspect/ElasticUnifiedLog.scala
close https://github.com/AutoMQ/automq-for-kafka/issues/534
=> fix: callback fail when partition closing

tests/kafkatest/tests/core/reassign_partitions_test.py
close https://github.com/AutoMQ/automq-for-kafka/issues/575
=> fix(e2e): await clean up task start

README.md
Fix quick start url address in readme. The original url will redirect a page not found.
=> fix: quick start doc address

build.gradle, checkstyle/import-control.xml, core/src/main/scala/kafka/log/stream/s3/metadata/StreamMetadataManager.java, core/src/test/java/kafka/log/stream/s3/StreamMetadataManagerTest.java, metadata/src/main/java/org/apache/kafka/controller/stream/StreamControlManager.java, metadata/src/main/java/org/apache/kafka/image/S3StreamsMetadataImage.java, metadata/src/main/java/org/apache/kafka/metadata/stream/S3StreamSetObject.java, metadata/src/test/java/org/apache/kafka/controller/StreamControlManagerTest.java, metadata/src/test/java/org/apache/kafka/image/NodeMetadataImageTest.java, metadata/src/test/java/org/apache/kafka/image/S3StreamsMetadataImageTest.java, metadata/src/test/java/org/apache/kafka/metadata/stream/SortedStreamSetObjectsListTest.java
close https://github.com/AutoMQ/automq-for-kafka/issues/602
=> feat(issues602): compress stream set object data

core/src/main/java/kafka/autobalancer/common/Resource.java, core/src/main/java/kafka/autobalancer/config/AutoBalancerMetricsReporterConfig.java, core/src/main/java/kafka/autobalancer/metricsreporter/AutoBalancerMetricsReporter.java, core/src/main/java/kafka/autobalancer/metricsreporter/metric/MetricsUtils.java, core/src/main/java/kafka/autobalancer/model/BrokerUpdater.java
change autobalancer capacity unit to bytes to be consistent with s3 network bandwidth configuration
=> feat(core): change autobalancer capacity unit to bytes

core/src/test/java/kafka/log/stream/s3/StreamMetadataManagerTest.java, metadata/src/main/java/org/apache/kafka/image/DeltaMap.java, metadata/src/main/java/org/apache/kafka/image/NodeS3StreamSetObjectMetadataImage.java, metadata/src/main/java/org/apache/kafka/image/NodeS3WALMetadataDelta.java, metadata/src/main/java/org/apache/kafka/image/S3ObjectsDelta.java, metadata/src/main/java/org/apache/kafka/image/S3StreamsMetadataDelta.java, metadata/src/main/java/org/apache/kafka/image/S3StreamsMetadataImage.java, metadata/src/test/java/org/apache/kafka/image/DeltaMapTest.java, metadata/src/test/java/org/apache/kafka/image/NodeMetadataImageTest.java, metadata/src/test/java/org/apache/kafka/image/S3StreamsMetadataImageTest.java
https://github.com/AutoMQ/automq-for-kafka/issues/618
=> feat(metadata): replace image map to delta map

automq_release.py
=> ci: Release 1.0.0 rc4

core/src/main/scala/kafka/cluster/Partition.scala
=> perf: return fast when the `fetchOffset` equals to the `confirmOffset`

bin/kafka-run-class.sh, config/kraft/broker.properties, config/kraft/controller.properties, config/kraft/server.properties, core/src/main/java/kafka/autobalancer/config/AutoBalancerConfig.java, core/src/main/scala/kafka/server/KafkaConfig.scala
close https://github.com/AutoMQ/automq-for-kafka/issues/662
=> feat(issues662): make default config adapt to 2c16g

build.gradle, gradle/dependencies.gradle, s3shell-kafka-sdk/src/main/java/com/automq/s3shell/sdk/auth/CredentialsProviderHolder.java
Credential provider holder offer a global singleton AwsCredentialProvider instance. This holder help invokers to shield the difference between multi-cloud and auth-type.
=> feat: add credential provider holder

metadata/src/main/java/org/apache/kafka/controller/ClusterControlManager.java, metadata/src/main/java/org/apache/kafka/controller/QuorumController.java, metadata/src/main/java/org/apache/kafka/controller/stream/StreamControlManager.java, metadata/src/test/java/org/apache/kafka/controller/StreamControlManagerTest.java
close https://github.com/AutoMQ/automq-for-kafka/issues/665
=> feat(issues665): clean up scale-in nodes' objects

core/src/main/scala/kafka/log/streamaspect/ElasticLog.scala
close https://github.com/AutoMQ/automq-for-kafka/issues/709
=> fix(log): make txn read async to avoid deadlock

core/src/main/java/kafka/autobalancer/LoadRetriever.java, core/src/main/java/kafka/autobalancer/model/ClusterModel.java
to prevent broker timestamp out-of-sync
=> fix(core): use partition metrics time as broker time

docker/telemetry/docker-compose.yaml, docker/telemetry/grafana/provisioning/dashboards/automq-for-kafka-dashboard.json, docker/telemetry/otel/otel-collector-config.yaml, docker/telemetry/prometheus/prometheus.yml
- use job & instance labels to match cluster id, node type and instance id, thus disable resource to labels translation
- configure otel collector to append suffix to metrics name
=> feat(core): refine exported metrics and dashboard

core/src/main/scala/kafka/log/streamaspect/ElasticLogFileRecords.java, core/src/test/scala/unit/kafka/log/streamaspect/ElasticLogTest.scala
close https://github.com/AutoMQ/automq-for-kafka/issues/754
=> fix(issues754): fix consume aborted txn

config/kraft/broker.properties, config/kraft/server.properties, kshell-sdk/src/main/java/com/automq/s3shell/sdk/model/S3Url.java
=> fix: don't deprecate s3.wal.path, plus a minor polish of s3url

core/src/main/scala/kafka/network/SocketServer.scala
close https://github.com/AutoMQ/automq-for-kafka/issues/751
=> fix(issues751): support quota throttling

core/src/main/scala/kafka/log/stream/s3/network/ControllerRequestSender.java, core/src/test/java/kafka/log/stream/s3/ControllerRequestSenderTest.java
close https://github.com/AutoMQ/automq-for-kafka/issues/764
=> fix(isssue764): ControllerRequestSender stuck

docker/telemetry/grafana/provisioning/dashboards/Developer/detailed.json, docker/telemetry/grafana/provisioning/dashboards/User/cluster.json, docker/telemetry/grafana/provisioning/dashboards/User/topic.json
present S3 request error rate as time series instead of pie chart
=> feat(dashboard): refine dashboards

tests/kafkatest/services/transactional_message_copier.py, tests/kafkatest/tests/core/group_mode_transactions_test.py, tools/src/main/java/org/apache/kafka/tools/TransactionalMessageCopier.java
=> fix(e2e): add consumer api timeout to 90s in hard bounce tests

core/src/main/scala/kafka/log/stream/s3/objects/ControllerObjectManager.java, core/src/main/scala/kafka/log/streamaspect/MetaStream.java, metadata/src/main/java/org/apache/kafka/controller/stream/StreamControlManager.java, metadata/src/test/java/org/apache/kafka/controller/StreamControlManagerTest.java
close https://github.com/AutoMQ/automq-for-kafka/issues/801
=> feat(issues801): stream trim only update stream metadata

clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java
=> fix(pr-827): fix release `PooledMemoryRecords` twice

tools/src/main/java/org/apache/kafka/tools/automq/GenerateS3UrlCmd.java
=> fix(tools): create s3url pathStyle not used

tools/src/main/java/org/apache/kafka/tools/automq/GenerateStartCmdCmd.java
When a node is both a broker and a controller, it will output the startup command if it is a broker+controller, and it will output the startup command if it is only a broker
当节点即使broker又是controller时，会输出其是broker+controller的启动命令，又会输出其仅是broker的启动命令
=> fix(tools): controllerOnlyMode is false no extra commands will be output

build.gradle, core/src/main/scala/kafka/server/streamaspect/ElasticReplicaManager.scala, gradle/dependencies.gradle, metadata/src/main/java/org/apache/kafka/image/NodeS3StreamSetObjectMetadataImage.java, metadata/src/main/java/org/apache/kafka/image/S3StreamsMetadataImage.java, metadata/src/main/java/org/apache/kafka/image/StreamOffsetIndexMap.java, metadata/src/main/java/org/apache/kafka/metadata/stream/S3StreamSetObject.java, metadata/src/test/java/org/apache/kafka/image/StreamOffsetIndexMapTest.java, s3stream/src/main/java/com/automq/stream/s3/ByteBufAlloc.java, s3stream/src/main/java/com/automq/stream/s3/S3Stream.java, s3stream/src/main/java/com/automq/stream/s3/cache/DefaultS3BlockCache.java, s3stream/src/main/java/com/automq/stream/s3/cache/ReadAheadAgent.java, s3stream/src/main/java/com/automq/stream/s3/cache/ReadAheadManager.java, s3stream/src/main/java/com/automq/stream/s3/cache/StreamReader.java, s3stream/src/main/java/com/automq/stream/s3/metrics/AttributesUtils.java, s3stream/src/main/java/com/automq/stream/s3/metrics/S3StreamMetricsConstant.java, s3stream/src/main/java/com/automq/stream/s3/metrics/S3StreamMetricsManager.java, s3stream/src/main/java/com/automq/stream/s3/metrics/stats/StorageOperationStats.java, s3stream/src/main/java/com/automq/stream/s3/operator/DefaultS3Operator.java, s3stream/src/main/java/com/automq/stream/utils/FutureUtil.java, s3stream/src/test/java/com/automq/stream/s3/cache/StreamReaderTest.java
1. adjust block cache memory limit and s3 r/w concurrency adaptively
2. add stream set object index to speed up sso lookup
3. increased fetch limiter quota in ReplicaManager
4. increased s3 operator read callback thread pool size
5. increased read ahead agent cache size
6. use seperated thread pool for block cache callback
7. add more comprehensive metrics to trace block cache performance (debug level)
=> feat(core): optimize block cache performance for high-spec node

core/src/main/java/kafka/autobalancer/LoadRetriever.java, core/src/main/java/kafka/autobalancer/detector/AnomalyDetector.java
close #989
* Enhancement AnomalyDetector log throwable and exit loop.
* Enhancement LoadRetriever log throwable and exit loop.
=> fix(core): enhancement AnomalyDetector and LoadRetriever

s3stream/src/main/java/com/automq/stream/s3/S3Storage.java, s3stream/src/main/java/com/automq/stream/s3/cache/LogCache.java
=> revert(s3stream): "perf(s3stream): only read the first record from log cache before reading block cache"

s3stream/src/main/java/com/automq/stream/s3/operator/DefaultS3Operator.java
=> fix(s3stream): fail fast if openssl not available

config/connect-log4j.properties, config/log4j.properties
This PR cherry-picks a fix from the main branch to the 1.0 branch, addressing the logging issue outlined in #1033 by switching from DailyRollingFileAppender to RollingFileAppender.
=> build(issues1033): switch log appender from DailyRollingFileAppender to RollingFileAppender #1092

core/src/main/java/kafka/autobalancer/LoadRetriever.java, core/src/main/java/kafka/autobalancer/common/types/MetricTypes.java, core/src/main/java/kafka/autobalancer/common/types/RawMetricTypes.java, core/src/main/java/kafka/autobalancer/common/types/metrics/AbnormalLatency.java, core/src/main/java/kafka/autobalancer/common/types/metrics/AbnormalMetric.java, core/src/main/java/kafka/autobalancer/common/types/metrics/AbnormalQueueSize.java, core/src/main/java/kafka/autobalancer/common/types/metrics/AbstractSimpleAbnormalMetric.java, core/src/main/java/kafka/autobalancer/detector/AnomalyDetector.java, core/src/main/java/kafka/autobalancer/goals/AbstractResourceDistributionGoal.java, core/src/main/java/kafka/autobalancer/goals/AbstractResourceGoal.java, core/src/main/java/kafka/autobalancer/metricsreporter/AutoBalancerMetricsReporter.java, core/src/main/java/kafka/autobalancer/metricsreporter/metric/BrokerMetrics.java, core/src/main/java/kafka/autobalancer/metricsreporter/metric/MetricsUtils.java, core/src/main/java/kafka/autobalancer/model/BrokerUpdater.java, core/src/main/java/kafka/autobalancer/model/ClusterModelSnapshot.java, core/src/main/java/kafka/autobalancer/model/MetricValueSequence.java, core/src/main/java/kafka/autobalancer/model/Snapshot.java, core/src/main/java/kafka/autobalancer/model/TopicPartitionReplicaUpdater.java, core/src/test/java/kafka/autobalancer/detector/AnomalyDetectorTest.java, core/src/test/java/kafka/autobalancer/goals/AbstractResourceUsageDistributionGoalTest.java, core/src/test/java/kafka/autobalancer/metricsreporter/AutoBalancerMetricsReporterTest.java, core/src/test/java/kafka/autobalancer/metricsreporter/metric/MetricSerdeTest.java, core/src/test/java/kafka/autobalancer/metricsreporter/metric/MetricsUtilsTest.java, core/src/test/java/kafka/autobalancer/model/ClusterModelTest.java, core/src/test/java/kafka/autobalancer/model/MetricValueSequenceTest.java
This PR is part of #1120 which implements slow broker detection in controller side. Client-side metrics reporting is yet to be implemented.
- BrokerMetrics is introduced to represent broker-wide metrics, such as append latency, append queue size, fetch latency and fetch queue size
- The metrics used to detect slow broker implementes interface of AbnormalMetric, which currently use a simple threshold to mark a abnormal status and will be optimized to using historical data and peer measurement later.
=> feat(issue1120): support slow broker detect in controller

core/src/main/java/kafka/autobalancer/LoadRetriever.java, core/src/main/java/kafka/autobalancer/common/types/RawMetricTypes.java, core/src/main/java/kafka/autobalancer/detector/AnomalyDetector.java, core/src/main/java/kafka/autobalancer/metricsreporter/AutoBalancerMetricsReporter.java, core/src/main/java/kafka/autobalancer/metricsreporter/metric/AutoBalancerMetrics.java, core/src/main/java/kafka/autobalancer/metricsreporter/metric/BrokerMetrics.java, core/src/main/java/kafka/autobalancer/metricsreporter/metric/DeltaHistogram.java, core/src/main/java/kafka/autobalancer/metricsreporter/metric/MetricSerde.java, core/src/main/java/kafka/autobalancer/metricsreporter/metric/TopicPartitionMetrics.java, core/src/main/java/kafka/autobalancer/model/BrokerUpdater.java, core/src/main/java/kafka/autobalancer/model/MetricValueSequence.java, core/src/main/java/kafka/autobalancer/model/Snapshot.java, core/src/test/java/kafka/autobalancer/detector/AnomalyDetectorTest.java, core/src/test/java/kafka/autobalancer/metricsreporter/AutoBalancerMetricsReporterTest.java, core/src/test/java/kafka/autobalancer/model/ClusterModelTest.java, s3stream/src/main/java/com/automq/stream/s3/S3Stream.java, s3stream/src/main/java/com/automq/stream/s3/metrics/S3StreamMetricsConstant.java, s3stream/src/main/java/com/automq/stream/s3/metrics/S3StreamMetricsManager.java, s3stream/src/main/java/com/automq/stream/s3/metrics/TimerUtil.java, server-common/src/main/java/org/apache/kafka/server/metrics/s3stream/S3StreamKafkaMetricsConstants.java, server-common/src/main/java/org/apache/kafka/server/metrics/s3stream/S3StreamKafkaMetricsManager.java
This PR is part of #1120 which implements client-side broker-level metrics reporting.
Currently a broker will marked as "slow" if any of the following conditions is met:
1. latest append stream latency exceeds 100ms
2. maximum pending append stream request latency exceeds 10s
3. maximum pending fetch stream request latency exceeds 10s 
If a slow broker is detected, no additional partitions will be assigned to it and value of metric kafka_stream_slow_broker_count with corresponding label "node_id=x" will be set to 1
=> feat(issue1120): support reporting broker metrics in AutoBalancerMetricsReporter

s3stream/src/test/java/com/automq/stream/s3/operator/MultiPartWriterTest.java
* Using a lock to ensure that the writing order of `writeContentLengths` and `uploadPartRequests` remains consistent.
=> fix(issues1072): fix MultiPartWriterTest unstable test

metadata/src/main/java/org/apache/kafka/controller/stream/S3ObjectControlManager.java
The same as https://github.com/AutoMQ/automq/pull/1172
=> feat(issues1171): improve objects deletion performance

core/src/main/java/kafka/autobalancer/AutoBalancerManager.java, core/src/main/java/kafka/autobalancer/config/AutoBalancerControllerConfig.java, core/src/main/java/kafka/autobalancer/detector/AnomalyDetector.java, core/src/main/java/kafka/autobalancer/detector/AnomalyDetectorBuilder.java, core/src/main/java/kafka/autobalancer/executor/ActionExecutorService.java, core/src/main/java/kafka/autobalancer/executor/ControllerActionExecutorService.java, core/src/test/java/kafka/autobalancer/ControllerActionExecutorServiceTest.java, core/src/test/java/kafka/autobalancer/detector/AnomalyDetectorTest.java
a fixed interval between each execution of actions
1. actions will be grouped into batches, actions within the same batch will be submitted to controller at once.
2. batching rules:
1. number of partitions from same topic in a batch exceeds half of the total partition number of that topic
2. number of partition closing/openning operation of a broker in a batch exceeds the max execution concurrency (50 by default)
3. wait for a fixed interval before executing the next action batch
=> feat(issue1179): accelerate partition reassignments on load balancing

core/src/main/scala/kafka/server/ReplicaManager.scala
main branch already fix this in https://github.com/AutoMQ/automq/pull/1180
=> fix(core): fix leader fast ABA reassign cause epoch outdated

core/src/main/java/kafka/autobalancer/goals/AbstractGoal.java, core/src/main/java/kafka/autobalancer/goals/AbstractResourceDistributionGoal.java, core/src/main/java/kafka/autobalancer/goals/AbstractResourceGoal.java, core/src/test/java/kafka/autobalancer/goals/AbstractResourceUsageDistributionGoalTest.java
This is part of #668
Swap action is rarely effective for load balancing in most cases, and the time cost to derive a valid swap action grows exponentially with the number of overall partitions, so it's better to disable it until we find a better way to solve this issue.
=> feat(issue668): disable swap action temporarily

core/src/main/scala/kafka/log/stream/s3/objects/ControllerObjectManager.java, metadata/src/test/java/org/apache/kafka/image/S3StreamMetadataImageTest.java, s3stream/src/main/java/com/automq/stream/s3/S3Storage.java, s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/StreamReader.java, s3stream/src/test/java/com/automq/stream/s3/cache/blockcache/StreamReaderTest.java
- Add #loadMoreBlocksWithoutData(endOffset) to avoid stream reader busy loop #getObjects when metadata replay delay.
=> fix(s3stream): fix stream reader busy loop when metadata replay delay

connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/AutoMQIdentityReplicationPolicy.java
=> feat(MM2): allow customizing MM2 offset-syncs/checkpoints/heartbeats topic easily

core/src/main/scala/kafka/log/streamaspect/DefaultOpenStreamChecker.java, core/src/main/scala/kafka/log/streamaspect/ElasticLog.scala, core/src/main/scala/kafka/log/streamaspect/OpenStreamChecker.java
fix https://github.com/AutoMQ/automq/issues/1169
=> fix(log): fix open stream checker

s3stream/src/main/java/com/automq/stream/s3/S3Storage.java, s3stream/src/main/java/com/automq/stream/s3/wal/BlockWALService.java
`WriteAheadLog#start()` is called twice during failover in:
- `Failover#FailoverTask#failover()`
- `S3Storage#recover(WALMetadata, StreamManager, ObjectManager, Logger)`
=> fix(s3stream): avoid starting wal twice during failover

core/src/main/scala/kafka/server/ReplicaManager.scala
Clean up the consumption offset for the deleted partitions that do not belong to the current broker.
=> fix(metadata): clean up the consumption offset for the deleted partitions

tools/src/main/java/org/apache/kafka/tools/automq/PerfCommand.java, tools/src/main/java/org/apache/kafka/tools/automq/perf/ConsumerService.java, tools/src/main/java/org/apache/kafka/tools/automq/perf/PerfConfig.java, tools/src/main/java/org/apache/kafka/tools/automq/perf/TopicService.java
See commit messages for more details.
=> feat(tools/perf): optimizing user experience

s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/StreamReader.java
close https://github.com/AutoMQ/automq/issues/1302
=> fix(issues1302): block bytebuf leak

metadata/src/main/java/org/apache/kafka/controller/stream/StreamControlManager.java, metadata/src/test/java/org/apache/kafka/controller/StreamControlManagerTest.java
close https://github.com/AutoMQ/automq/issues/1222#issuecomment-2132812938
=> fix(issues1222): fix stream advance check

s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/StreamReader.java
close https://github.com/AutoMQ/automq/issues/1302
=> fix(issues1302): fix StreamReader buf LEAK

core/src/main/scala/kafka/log/stream/s3/streams/ControllerStreamManager.java, s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/StreamReader.java
=> chore(s3stream): add `toString` methods to fix logs

core/src/main/scala/kafka/log/stream/s3/metadata/StreamMetadataManager.java, metadata/src/main/java/org/apache/kafka/image/NodeS3StreamSetObjectMetadataImage.java, metadata/src/main/java/org/apache/kafka/image/S3StreamMetadataImage.java, metadata/src/main/java/org/apache/kafka/image/S3StreamsMetadataImage.java, metadata/src/main/java/org/apache/kafka/image/StreamOffsetIndexMap.java, metadata/src/test/java/org/apache/kafka/image/S3StreamsMetadataImageTest.java
1. use volatile field to store MetadataImage avoid acquire lock when kraft metadata update
2. when access metadata store MetadataImage to local field without hold locks.
3. for the index structure in MetadataImage use lock to trigger index build and after build success the access is volatile access.
4. avoid get list.size() in for iter.
1. add concurrent access metadata test to check the access is right.
=> perf(s3stream): reduce lock granularity in `StreamMetadataManager`

s3stream/src/main/java/com/automq/stream/s3/operator/AbstractObjectStorage.java, s3stream/src/main/java/com/automq/stream/s3/operator/AwsObjectStorage.java
* The logic of MergeRead and acquireReadPermit has been extracted to `AbstractObjectStorage.java`
* Most of the logic remains consistent with before, except that the `String path` in ReadTask has been replaced with `S3ObjectMetadata s3ObjectMetadata`.
* `AwsObjectStorage.java` is responsible for performing the rangeRead operations from S3, `doRangeRead`.
=> feat(s3stream): add aws s3 rangeRead implementation for object storage

CONTRIBUTING_GUIDE.md
1. Remove Pull Request Handbook
2. Remove Connector Guidelines
The Pull Request Handbook file and The connector guideline were Airbyte specific, so they have been excluded.
=> fix(docs): fix contributing guide

examples/src/main/java/kafka/examples/TransactionProducer.java
refactor TransactionProducer class.
1. replace server configuration to use static properties instead of hardcoded value.
2. remove batch size initialization code
it is unnecessary, refer to the following [link ](https://github.com/AutoMQ/automq/blob/2821f2462e88e35506c8d0a57bf6b09c548c12a2/clients/src/main/java/org/apache/kafka/clients/producer/KafkaProducer.java#L432)
=> chore(examples): remove hardcoded value in TransactionProducer 

s3stream/src/main/java/com/automq/stream/s3/CompositeObject.java, s3stream/src/main/java/com/automq/stream/s3/CompositeObjectReader.java, s3stream/src/main/java/com/automq/stream/s3/CompositeObjectWriter.java, s3stream/src/main/java/com/automq/stream/s3/Constants.java, s3stream/src/main/java/com/automq/stream/s3/DataBlockIndex.java, s3stream/src/main/java/com/automq/stream/s3/ObjectReader.java, s3stream/src/main/java/com/automq/stream/s3/ObjectWriter.java, s3stream/src/main/java/com/automq/stream/s3/StreamDataBlock.java, s3stream/src/main/java/com/automq/stream/s3/StreamObjectCompactor.java, s3stream/src/main/java/com/automq/stream/s3/cache/StreamReader.java, s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/StreamReaders.java, s3stream/src/main/java/com/automq/stream/s3/compact/operator/DataBlockReader.java, s3stream/src/main/java/com/automq/stream/s3/metadata/S3ObjectMetadata.java, s3stream/src/main/java/com/automq/stream/s3/metadata/S3ObjectType.java, s3stream/src/test/java/com/automq/stream/s3/CompositeObjectTest.java, s3stream/src/test/java/com/automq/stream/s3/DeltaWALUploadTaskTest.java, s3stream/src/test/java/com/automq/stream/s3/ObjectReaderTest.java, s3stream/src/test/java/com/automq/stream/s3/ObjectWriterTest.java, s3stream/src/test/java/com/automq/stream/s3/StreamObjectCompactorTest.java, s3stream/src/test/java/com/automq/stream/s3/cache/ObjectReaderLRUCacheTest.java, s3stream/src/test/java/com/automq/stream/s3/cache/blockcache/MockObject.java
Main modification：
- s3stream/src/main/java/com/automq/stream/s3/CompositeObjectReader.java
- s3stream/src/main/java/com/automq/stream/s3/CompositeObjectWriter.java
=> feat(s3stream): composite object reader&writer

s3stream/src/main/java/com/automq/stream/s3/compact/StreamObjectCompactor.java, s3stream/src/main/java/com/automq/stream/s3/operator/MemoryS3Operator.java, s3stream/src/main/java/com/automq/stream/s3/operator/MultiPartWriter.java, s3stream/src/main/java/com/automq/stream/s3/operator/MultiPartWriterV2.java, s3stream/src/main/java/com/automq/stream/s3/operator/ObjectStorage.java, s3stream/src/main/java/com/automq/stream/s3/operator/ProxyWriter.java, s3stream/src/main/java/com/automq/stream/s3/operator/ProxyWriterV2.java, s3stream/src/main/java/com/automq/stream/s3/operator/Writer.java, s3stream/src/test/java/com/automq/stream/s3/operator/MultiPartWriterTest.java, s3stream/src/test/java/com/automq/stream/s3/operator/ProxyWriterTest.java
* update copyWrite parameter to accept S3ObjectMetadata
* The logic of `ProxyWriterV2` and `MultiPartWriterV2` is essentially the same as that of `ProxyWriter` and `MultiPartWriterV2`, with the primary changes being:
* Utilization of the new object storage abstraction `AbstractObjectStorage`.
* Replacement of `Context` and `ThrottleStrategy` with `WriteOptions`.
=> feat(s3stream): object storage writer

core/src/main/java/kafka/autobalancer/common/Action.java, core/src/main/java/kafka/autobalancer/config/AutoBalancerControllerConfig.java, core/src/main/java/kafka/autobalancer/detector/AnomalyDetector.java, core/src/main/java/kafka/autobalancer/goals/AbstractGoal.java, core/src/main/java/kafka/autobalancer/goals/AbstractResourceDistributionGoal.java, core/src/main/java/kafka/autobalancer/goals/AbstractResourceGoal.java, core/src/main/java/kafka/autobalancer/goals/AbstractResourceUsageDistributionGoal.java, core/src/main/java/kafka/autobalancer/goals/Goal.java, core/src/main/java/kafka/autobalancer/goals/NetworkInUsageDistributionGoal.java, core/src/main/java/kafka/autobalancer/goals/NetworkOutUsageDistributionGoal.java, core/src/main/java/kafka/autobalancer/model/ClusterModelSnapshot.java, core/src/test/java/kafka/autobalancer/detector/AnomalyDetectorTest.java, core/src/test/java/kafka/autobalancer/goals/ResourceUsageDistributionGoalTest.java
A trivial scheduling involves of a series of partition reassignments that minimally impacts the broker load, which can be easily affect by load fluctuation.
After optimizing each broker for a specified goal, collect the overall load impact for that broker from all actions derived from the previous optimization and check if the ratio of the load change and load avg is above the trivial ratio threshold (0.05 by default), and undo those actions which have been considered as trivial 
#1134
=> feat(issue1134): prevent trivial scheduling

README.md
=> feat(issue1462): Optimize the Readme. #1462

s3stream/src/main/java/com/automq/stream/s3/wal/impl/block/BlockWALService.java
current code if wal sliding window not expand 
the wal header won't flush to UNGRACEFULLY
=> fix(s3stream): ensure wal header shutdown type UNGRACEFULLY when startup

core/src/main/scala/kafka/log/streamaspect/ElasticTimeIndex.java, core/src/main/scala/kafka/log/streamaspect/ElasticTransactionIndex.java, core/src/main/scala/kafka/log/streamaspect/cache/FileCache.java, core/src/test/java/kafka/log/streamaspect/ElasticTimeIndexTest.java, core/src/test/java/kafka/log/streamaspect/ElasticTransactionIndexTest.java, core/src/test/java/kafka/log/streamaspect/cache/FileCacheTest.java
the position used in file cache is relative to the start offset of a segment in the underlying stream, so different segment from same partition should not share the same block map in order to avoid position conflict
=> fix(s3stream): use segment-unique id as file cache key

core/src/main/scala/kafka/log/LocalLog.scala, core/src/main/scala/kafka/log/UnifiedLog.scala, core/src/main/scala/kafka/log/streamaspect/ElasticLog.scala, core/src/main/scala/kafka/log/streamaspect/ElasticUnifiedLog.scala
Closes the issue https://github.com/AutoMQ/automq/issues/1100
=> refactor(log): introduce async close

.idea/copyright/BSL.xml, core/src/main/scala/kafka/log/stream/s3/DefaultS3Client.java, core/src/main/scala/kafka/log/stream/s3/metadata/StreamMetadataManager.java, metadata/src/main/java/org/apache/kafka/image/NodeS3StreamSetObjectMetadataImage.java, metadata/src/main/java/org/apache/kafka/image/S3StreamsMetadataImage.java, metadata/src/test/java/org/apache/kafka/image/S3StreamsMetadataImageTest.java, s3stream/src/main/java/com/automq/stream/s3/DeltaWALUploadTask.java, s3stream/src/main/java/com/automq/stream/s3/S3Storage.java, s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/DefaultObjectReaderFactory.java, s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/ObjectReaderFactory.java, s3stream/src/main/java/com/automq/stream/s3/compact/CompactionManager.java, s3stream/src/main/java/com/automq/stream/s3/index/LocalStreamRangeIndexCache.java, s3stream/src/main/java/com/automq/stream/s3/index/NodeRangeIndexCache.java, s3stream/src/main/java/com/automq/stream/s3/index/RangeIndex.java, s3stream/src/main/java/com/automq/stream/s3/index/SparseRangeIndex.java, s3stream/src/main/java/com/automq/stream/s3/metadata/ObjectUtils.java, s3stream/src/test/java/com/automq/stream/s3/DeltaWALUploadTaskTest.java, s3stream/src/test/java/com/automq/stream/s3/S3StorageTest.java, s3stream/src/test/java/com/automq/stream/s3/cache/blockcache/StreamReaderTest.java, s3stream/src/test/java/com/automq/stream/s3/index/LocalStreamRangeIndexCacheTest.java, s3stream/src/test/java/com/automq/stream/s3/index/NodeRangeIndexCacheTest.java, s3stream/src/test/java/com/automq/stream/s3/index/SparseRangeIndexTest.java
test case: single node, 5000 partition, 170+sso
before: open 5001 / make leader 0 / close 0 partitions cost 6185ms
after:    open 5001 / make leader 0 / close 0 partitions cost 2411ms
=> feat(core): optimize indexing performance by using sparse index cache

s3stream/src/main/java/com/automq/stream/s3/S3StreamClient.java, s3stream/src/main/java/com/automq/stream/s3/compact/StreamObjectCompactor.java, s3stream/src/test/java/com/automq/stream/s3/compact/StreamObjectCompactorTest.java, s3stream/src/test/java/com/automq/stream/s3/operator/DeleteObjectsAccumulatorTest.java
1. support MAJOR_V1 compaction skip object which size is below the MINOR_V1_COMPACTION_SIZE.
2. default skip logic is disabled.
=> feat(s3stream): support config MAJOR_V1 skip compact small object

core/src/main/java/kafka/autobalancer/model/ClusterModel.java, metadata/src/main/java/org/apache/kafka/controller/es/ClusterStats.java, metadata/src/main/java/org/apache/kafka/controller/es/LoadAwarePartitionLeaderSelector.java, metadata/src/test/java/org/apache/kafka/controller/es/LoadAwarePartitionLeaderSelectorTest.java, server-common/src/main/java/org/apache/kafka/common/WeightedRandomList.java
assign partitions to brokers based on a probability that is inversely proportional to the broker's load to prevent over-concentrated distribution.
=> feat(core): optimize LoadAwarePartitionLeaderSelector

core/src/main/resources/jmx/rules/broker.yaml, core/src/main/scala/kafka/server/streamaspect/BrokerQuotaManager.scala
Export five new metrics:
- kafka_broker_quota_value_record
- kafka_broker_quota_throttle_time
- kafka_broker_connection_accept_rate
- kafka_listener_connection_accept_rate
- kafka_listener_connection_accept_throttle_time
=> feat(core): add quota metrics into jmx metrics mapping

s3stream/src/main/java/com/automq/stream/s3/cache/LogCache.java, s3stream/src/main/java/com/automq/stream/s3/model/StreamRecordBatch.java
=> perf(s3stream): increase the object overhead of `StreamRecordBatch`

core/src/main/scala/kafka/log/streamaspect/ElasticLog.scala, s3stream/src/main/java/com/automq/stream/s3/DeltaWALUploadTask.java, s3stream/src/main/java/com/automq/stream/s3/S3Storage.java, s3stream/src/main/java/com/automq/stream/s3/metrics/S3StreamMetricsConstant.java, s3stream/src/main/java/com/automq/stream/s3/metrics/S3StreamMetricsManager.java, s3stream/src/main/java/com/automq/stream/s3/metrics/stats/StorageOperationStats.java, s3stream/src/main/java/com/automq/stream/s3/metrics/wrapper/DeltaHistogram.java, s3stream/src/main/java/com/automq/stream/s3/metrics/wrapper/HistogramInstrument.java, s3stream/src/main/java/com/automq/stream/s3/metrics/wrapper/HistogramMetric.java, s3stream/src/main/java/com/automq/stream/utils/AsyncRateLimiter.java, s3stream/src/main/java/com/automq/stream/utils/FutureTicker.java
we want to optimize the partition failover time. and we found the main part in partition clean shutdown failover is stream close.
and the stream close is slow because of the Upload RateLimit when upload.
and the FutureTicker also will cause the force upload task finish in long time. which at most delay 500ms and the 500ms delay may cause the upload data amount much larger.
1. support p99, p95 p50 in DeltaHistogram. use HdrHistogram which calculate p99 in low overhead.
2. support DeltaWALUploadTask limiter burst mode which cal make all the acquire fast pass.
3. support FutureTicker to wait small time when force upload.
------
kube800 the yellow line is enabled burst and wait at most 100ms when force upload.
kube801 the orange line is enabled burst and wait at most 500ms when force upload. …
=> feat(s3stream): support burst upload for upload WAL task to reduce failover time.

core/src/main/scala/kafka/log/streamaspect/ElasticLogSegmentManager.java, core/src/test/java/kafka/log/streamaspect/ElasticLogSegmentManagerTest.java
log 
```java
[2024-07-22 10:30:21,309] ERROR Uncaught exception in scheduled task 'delete-file' (org.apache.kafka.server.util.KafkaScheduler)
java.lang.OutOfMemoryError: Java heap space
at com.fasterxml.jackson.core.util.ByteArrayBuilder.toByteArray(ByteArrayBuilder.java:163)
at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsBytes(ObjectWriter.java:1164)
at kafka.log.streamaspect.ElasticLogMeta.encode(ElasticLogMeta.java:53)
at kafka.log.streamaspect.ElasticLogSegmentManager.asyncPersistLogMeta(ElasticLogSegmentManager.java:80)
at kafka.log.streamaspect.ElasticLogSegmentManager$EventListener.onEvent(ElasticLogSegmentManager.java:153)
at kafka.log.streamaspect.ElasticLogSegment.deleteIfExists(ElasticLogSegment.java:410)
at …
```
=> perf(core): batch persistent meta when delete large scale segment

core/src/main/scala/kafka/log/streamaspect/ElasticLogManager.scala
=> fix(ElasticLogManager): terminate the unending shutdown by completing `INIT_FUTURE`

s3stream/src/main/java/com/automq/stream/s3/wal/impl/object/ObjectWALConfig.java, s3stream/src/main/java/com/automq/stream/s3/wal/impl/object/RecordAccumulator.java, s3stream/src/test/java/com/automq/stream/s3/wal/impl/object/ObjectWALServiceTest.java, s3stream/src/test/java/com/automq/stream/s3/wal/impl/object/RecordAccumulatorTest.java
Limiting the content length and split requests in the standard S3 service may cause unnecessary API request costs. Therefore, it recommends enabling this feature only in the S3 express service.
=> feat(s3stream): add strictBathLimit option for s3 wal

s3stream/src/main/java/com/automq/stream/s3/operator/AbstractObjectStorage.java, s3stream/src/main/java/com/automq/stream/s3/operator/AwsObjectStorage.java, s3stream/src/main/java/com/automq/stream/s3/operator/DeleteObjectsAccumulator.java, s3stream/src/test/java/com/automq/stream/s3/operator/DeleteObjectsAccumulatorTest.java
* limit the number of deletions in a single batch and the maximum concurrency of deletion requests
=> refactor(s3stream): refactor batch delete objects

s3stream/src/main/java/com/automq/stream/s3/S3Storage.java, s3stream/src/main/java/com/automq/stream/s3/S3Stream.java
**Background**:
Due to the fact that the callback order of `CompletableFuture` follows a LIFO (Last In First Out) pattern, it leads to uncertainty and potentially significant delays in the execution timing of the `release` method for the current `StreamRecordBatch`.
We should ensure that such methods are executed with priority whenever possible.
com.automq.stream.s3.S3Storage#append
com.automq.stream.s3.S3Stream#append0
=> feat(s3stream): optimize the execution order of the release method for ByteBuf

clients/src/main/java/org/apache/kafka/common/utils/BufferSupplier.java, clients/src/test/java/org/apache/kafka/common/utils/GrowableMultiBufferSupplierTest.java, raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java
=> perf: use a new `GrowableMultiBufferSupplier` to avoid memory waste

s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/DataBlock.java
close https://github.com/AutoMQ/automq/issues/1798
=> fix(issues1798): force expired data block after create timestamp exceed FORCE_EXPIRED_DELTA_MILLS

s3stream/src/main/java/com/automq/stream/s3/wal/impl/object/RecordAccumulator.java
The deadlock occurs between:
- at com.automq.stream.s3.S3Storage.lambda$append0$16(S3Storage.java:488)
- at com.automq.stream.s3.wal.impl.object.RecordAccumulator.lambda$unsafeUpload$16(RecordAccumulator.java:531)
```log
"0-9-s3-read-cb-executor-1" #247 [4207] daemon prio=5 os_prio=0 cpu=1546.08ms elapsed=16773.60s tid=0x00007f1a5a4a9000 nid=4207 waiting on condition  [0x00007f1a38290000]
java.lang.Thread.State: WAITING (parking)
at jdk.internal.misc.Unsafe.park(java.base@22.0.2/Native Method)
- parking to wait for  <0x000004006c325990> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
at java.util.concurrent.locks.LockSupport.park(java.base@22.0.2/LockSupport.java:221)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@22.0.2/AbstractQueuedSynchroni …
```
=> fix(s3stream): fix deadlock issue

s3stream/src/main/java/com/automq/stream/s3/wal/impl/block/BlockWALService.java, s3stream/src/main/java/com/automq/stream/s3/wal/impl/block/SlidingWindowService.java, s3stream/src/main/java/com/automq/stream/s3/wal/util/WALChannel.java
The shutdown process gets stuck due to an `IOException` during shutdown:
=> fix(s3strea/wal): handle `IOException` during flushing WAL header

s3stream/src/main/java/com/automq/stream/s3/wal/impl/block/BlockWALService.java, s3stream/src/main/java/com/automq/stream/s3/wal/util/AbstractWALChannel.java, s3stream/src/main/java/com/automq/stream/s3/wal/util/WALBlockDeviceChannel.java, s3stream/src/main/java/com/automq/stream/s3/wal/util/WALCachedChannel.java, s3stream/src/main/java/com/automq/stream/s3/wal/util/WALChannel.java, s3stream/src/main/java/com/automq/stream/s3/wal/util/WALFileChannel.java, s3stream/src/test/java/com/automq/stream/s3/wal/impl/block/BlockWALServiceTest.java, s3stream/src/test/java/com/automq/stream/s3/wal/util/WALBlockDeviceChannelTest.java, s3stream/src/test/java/com/automq/stream/s3/wal/util/WALChannelTest.java
=> fix(s3stream/wal): fail all IO operations once the WAL is failed

metadata/src/test/java/org/apache/kafka/image/S3StreamsMetadataImageTest.java, s3stream/src/main/java/com/automq/stream/s3/compact/CompactionManager.java, s3stream/src/main/java/com/automq/stream/s3/index/LocalStreamRangeIndexCache.java, s3stream/src/main/java/com/automq/stream/s3/index/SparseRangeIndex.java, s3stream/src/main/java/com/automq/stream/s3/operator/ProxyWriter.java, s3stream/src/test/java/com/automq/stream/s3/index/LocalStreamRangeIndexCacheTest.java, s3stream/src/test/java/com/automq/stream/s3/index/MockRandom.java, s3stream/src/test/java/com/automq/stream/s3/index/SparseRangeIndexTest.java
same as https://github.com/AutoMQ/automq/pull/1832
=> feat(metadata): limit the size of sparse index cache

s3stream/src/test/java/com/automq/stream/s3/index/LocalStreamRangeIndexCacheTest.java
=> revert: enable `LocalStreamRangeIndexCacheTest#testEvict`

s3stream/src/test/java/com/automq/stream/s3/failover/FailoverTest.java
**Background:** 
The FailoverFactory#getWal method creates a new BlockWALService object each time it is called. Here, thenAnswer should be used instead of thenReturn,
however, the use of thenReturn did not affect the subsequent tests.
This also exposes the existing issues with the BlockWALService closed-loop.
This  [PR](https://github.com/AutoMQ/automq/pull/1625) contains an optimization plan for the current problem.
=> feat(wal): failoverTest optimization

s3stream/src/main/java/com/automq/stream/s3/S3Stream.java, s3stream/src/main/java/com/automq/stream/s3/wal/impl/block/BlockWALService.java
=> perf(s3stream): check the logger level before `trace` and `debug`

s3stream/src/main/java/com/automq/stream/FixedSizeByteBufPool.java, s3stream/src/main/java/com/automq/stream/s3/wal/common/Record.java, s3stream/src/main/java/com/automq/stream/s3/wal/common/RecordHeader.java, s3stream/src/main/java/com/automq/stream/s3/wal/impl/block/Block.java, s3stream/src/main/java/com/automq/stream/s3/wal/impl/block/BlockImpl.java, s3stream/src/main/java/com/automq/stream/s3/wal/impl/block/BlockWALService.java, s3stream/src/main/java/com/automq/stream/s3/wal/util/WALUtil.java, s3stream/src/test/java/com/automq/stream/FixedSizeByteBufPoolTest.java, s3stream/src/test/java/com/automq/stream/s3/wal/impl/block/BlockWALServiceTest.java
=> perf(s3stream/wal): reuse the `ByteBuf` for record headers

s3stream/src/main/java/com/automq/stream/FixedSizeByteBufPool.java, s3stream/src/main/java/com/automq/stream/s3/wal/common/Record.java, s3stream/src/main/java/com/automq/stream/s3/wal/common/RecordHeader.java, s3stream/src/main/java/com/automq/stream/s3/wal/impl/block/Block.java, s3stream/src/main/java/com/automq/stream/s3/wal/impl/block/BlockImpl.java, s3stream/src/main/java/com/automq/stream/s3/wal/impl/block/BlockWALService.java, s3stream/src/main/java/com/automq/stream/s3/wal/util/WALUtil.java, s3stream/src/test/java/com/automq/stream/FixedSizeByteBufPoolTest.java, s3stream/src/test/java/com/automq/stream/s3/wal/impl/block/BlockWALServiceTest.java
=> perf(s3stream/wal): reuse the `ByteBuf` for record headers (#1877)

s3stream/src/main/java/com/automq/stream/FixedSizeByteBufPool.java, s3stream/src/main/java/com/automq/stream/s3/wal/common/RecordHeader.java, s3stream/src/main/java/com/automq/stream/s3/wal/impl/object/ObjectWALService.java, s3stream/src/main/java/com/automq/stream/s3/wal/util/WALUtil.java, s3stream/src/test/java/com/automq/stream/s3/wal/impl/block/BlockWALServiceTest.java, s3stream/src/test/java/com/automq/stream/s3/wal/impl/object/ObjectWALServiceTest.java
=> perf(s3stream): optimize the critical section in s3 wal

core/src/main/java/kafka/autobalancer/detector/AnomalyDetector.java, core/src/main/java/kafka/autobalancer/model/BrokerUpdater.java, core/src/main/java/kafka/autobalancer/model/TopicPartitionReplicaUpdater.java, metadata/src/main/java/org/apache/kafka/image/S3StreamsMetadataImage.java, s3stream/src/main/java/com/automq/stream/s3/S3Storage.java, s3stream/src/main/java/com/automq/stream/s3/S3Stream.java, s3stream/src/main/java/com/automq/stream/s3/cache/LogCache.java, s3stream/src/main/java/com/automq/stream/s3/index/LocalStreamRangeIndexCache.java, s3stream/src/main/java/com/automq/stream/s3/index/NodeRangeIndexCache.java, s3stream/src/main/java/com/automq/stream/s3/metrics/S3StreamMetricsConstant.java, s3stream/src/main/java/com/automq/stream/s3/metrics/S3StreamMetricsManager.java, s3stream/src/main/java/com/automq/stream/s3/metrics/TimerUtil.java, s3stream/src/main/java/com/automq/stream/s3/metrics/stats/MetadataStats.java, s3stream/src/main/java/com/automq/stream/s3/operator/AbstractObjectStorage.java, s3stream/src/main/java/com/automq/stream/s3/wal/impl/block/BlockImpl.java, s3stream/src/main/java/com/automq/stream/s3/wal/impl/block/BlockWALService.java, s3stream/src/main/java/com/automq/stream/s3/wal/impl/block/SlidingWindowService.java
metrics added:
- kafka_stream_local_stream_range_index_cache_stream_num: The number of streams cached in local sparse index
- kafka_stream_local_stream_range_index_cache_size_bytes: The total size in bytes of local sparse index
- kafka_stream_node_range_index_cache_operation_count_total: The cumulative count of different type of operations on sparse index cache (update/invalidate/hit/miss)
- kafka_stream_get_objects_time_sum(50p/99p/max)_nanosecond: The delta time spend on determining which s3 objects to read from for a certain stream range
- kafka_stream_get_objects_time_count: The delta num of invoking getObjects method
=> feat(metadata): add metrics for sparse index cache monitor

server-common/src/main/java/org/apache/kafka/server/config/ServerLogConfigs.java
=> perf(config): increase the default index interval from 4KiB to 1MiB

s3stream/src/main/java/com/automq/stream/utils/threads/EventLoop.java
The visibility of the shutdown flag for the event loop and optimizations for graceful shutdown
=> feat(eventLoop): the visibility of the shutdown flag for the event loop and optimizations for graceful shutdown

s3stream/src/main/java/com/automq/stream/s3/ByteBufAlloc.java, s3stream/src/main/java/com/automq/stream/s3/operator/ObjectStorage.java, s3stream/src/main/java/com/automq/stream/s3/wal/impl/object/ObjectWALService.java, s3stream/src/main/java/com/automq/stream/s3/wal/impl/object/RecordAccumulator.java
=> fix(s3stream): resolve unintended buffer reuse

s3stream/src/main/java/com/automq/stream/s3/wal/impl/object/ObjectWALService.java
The `ByteBufSeqAlloc` preallocates large buffers but lacks a release mechanism. Making it static could serve as a workaround.
=> fix(s3stream): fix buffer leak

core/src/main/java/kafka/automq/AutoMQConfig.java, s3stream/src/main/java/com/automq/stream/s3/wal/impl/block/BlockWALService.java, s3stream/src/main/java/com/automq/stream/s3/wal/util/WALBlockDeviceChannel.java, s3stream/src/main/java/com/automq/stream/s3/wal/util/WALChannel.java, s3stream/src/test/java/com/automq/stream/s3/wal/util/WALChannelTest.java
1. the block device provider have limit on iobandwidth and iops. either one exceed the limit the write block channel time goes very high (cause by the block device qos)
2. when single node write request number is high. the write may exceed the limit iobandwidth for a little time but can cause the pending request accumlate and finally the broker will have very long write latency.
=> feat(s3stream): support limit write bandwidth for WALBlockDeviceChannel

core/src/main/java/kafka/automq/AutoMQConfig.java, metadata/src/main/java/org/apache/kafka/controller/QuorumController.java
1. decrease default max stream number per sso config to 20k, corresponds to 15k streams per node as recommended upper limit
2. increase single batch record size limit to 50k for worst case to force split a sso with 20k streams
=> feat(core): default configuration optimization

core/src/main/java/kafka/autobalancer/model/AbstractInstanceUpdater.java, core/src/main/java/kafka/autobalancer/model/ClusterModel.java, core/src/test/java/kafka/autobalancer/model/ClusterModelTest.java
give some exemption time (60s) for newly created partition to receive metrics before reporting it as out-of-sync to prevent false alert
=> feat(metrics): skip reporting metrics delay for newly created partition

docker/scripts/start.sh
This pull request includes a change in the `docker/scripts/start.sh` file to update the S3 bucket configuration for Kafka roles. The most important change is the modification of the S3 bucket configuration properties to use `authType=static` instead of `accessKey=static`.
Configuration updates:
* [`docker/scripts/start.sh`](diffhunk://#diff-4c4be7114665bf713eb5aa82e0c67369bd9c7fcea84ed16fe5d0b51ac07204dbL268-R269): Changed `s3.data.bucket` to `s3.data.buckets` and `s3.ops.bucket` to `s3.ops.buckets`, updating the S3 configuration to use `authType=static` instead of `accessKey=static`.
=> ci(main):  fix start sh

config/connect-log4j.properties
Update the log4j properties file to roll the log file when it reaches the specified size. The `MaxFileSize` option is set to 10MB and the `MaxBackupIndex` option is set to 11 to keep 11 backup files.
=> chore(config): update log4j properties

core/src/main/scala/kafka/raft/KafkaMetadataLog.scala
=> perf(kraft): decrease the index interval bytes of KRaft Log from 1MB to 4KB

core/src/main/resources/jmx/rules/broker.yaml, core/src/main/scala/kafka/network/RequestChannel.scala, core/src/main/scala/kafka/network/SocketServer.scala, core/src/main/scala/kafka/server/KafkaConfig.scala, core/src/main/scala/kafka/server/KafkaRequestHandler.scala, core/src/main/scala/kafka/server/streamaspect/ElasticKafkaApis.scala, core/src/main/scala/kafka/server/streamaspect/ElasticReplicaManager.scala, server/src/main/java/org/apache/kafka/network/SocketServerConfigs.java
=> perf: limit the inflight requests (#2100)

s3stream/src/main/java/com/automq/stream/s3/compact/CompactionManager.java
=> fix(issue2108): avoid blocking at the end of a compaction iteration when there are un-uploaded data

tools/src/main/java/org/apache/kafka/tools/automq/PerfCommand.java, tools/src/main/java/org/apache/kafka/tools/automq/perf/ConsumerService.java
=> feat(tools/perf): run benchmark without consumer

s3stream/src/main/java/com/automq/stream/s3/CompositeObjectReader.java, s3stream/src/main/java/com/automq/stream/s3/ObjectReader.java
=> fix(issue2139): prevent read object info from closed ObjectReader

README.md
Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [AutoMQ Guru](https://gurubase.io/g/automq) to Gurubase. AutoMQ Guru uses the data from this repo and data from the [docs](https://www.automq.com/docs) to answer questions by leveraging the LLM.
In this PR, I showcased the "AutoMQ Guru", which highlights that AutoMQ now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.
Additionally, if you want me to …
=> docs: Introducing AutoMQ Guru on Gurubase.io

core/src/main/scala/kafka/log/streamaspect/ElasticLogFileRecords.java
=> fix(stream): release `FetchResult`s if the subsequent fetch fails

core/src/main/scala/kafka/server/FetchSession.scala
=> fix: release `PooledMemoryRecords` if it's dropped in the fetch session

core/src/main/scala/kafka/log/streamaspect/ElasticLogSegment.java
=> fix: use the "adjusted" `maxSize` in `ElasticLogSegment#readAsync`

clients/src/main/java/org/apache/kafka/common/config/TopicConfig.java, core/src/main/java/kafka/automq/AutoMQConfig.java, core/src/main/scala/kafka/server/ControllerConfigurationValidator.scala, core/src/main/scala/kafka/server/KafkaConfig.scala, core/src/test/scala/unit/kafka/server/ControllerConfigurationValidatorTableTest.scala, core/src/test/scala/unit/kafka/server/ControllerConfigurationValidatorTest.scala, server-common/src/main/java/org/apache/kafka/server/config/ServerTopicConfigSynonyms.java, server-common/src/main/java/org/apache/kafka/server/record/TableTopicSchemaType.java, storage/src/main/java/org/apache/kafka/storage/internals/log/LogConfig.java
=> feat(config): add table topic conversion type configuration (#2203)

clients/src/main/java/org/apache/kafka/common/config/TopicConfig.java, storage/src/main/java/org/apache/kafka/storage/internals/log/LogConfig.java
cherry-pick https://github.com/AutoMQ/automq/pull/2247
=> feat(table): support partition & upsert config

automq-shell/src/main/java/com/automq/shell/commands/cluster/Deploy.java
Adapt to following Apache Kafka changes:
- KAFKA-16525; Dynamic KRaft network manager and channel: https://github.com/AutoMQ/automq/commit/459da479
- KAFKA-17048; Update docs for KIP-853: https://github.com/AutoMQ/automq/commit/c141acb6
=> fix(cli/deploy): override "controller.quorum.bootstrap.servers"

build.gradle, tools/src/main/java/org/apache/kafka/tools/automq/PerfCommand.java, tools/src/main/java/org/apache/kafka/tools/automq/perf/ConsumerService.java, tools/src/main/java/org/apache/kafka/tools/automq/perf/PerfConfig.java
=> feat(tools/perf): support to limit the max poll rate of consumers

s3stream/src/main/java/com/automq/stream/s3/wal/impl/block/BlockWALService.java
=> fix(s3stream/wal): increase max record size from 16MiB to 64MiB

s3stream/src/main/java/com/automq/stream/s3/operator/MultiPartWriter.java
=> fix(s3stream): skip waiting for pending part on release (#2316)

core/src/main/scala/kafka/network/SocketServer.scala
Use Option(variable).foreach  to avoid NullPointerException
=> fix(network): prevent NullPointerException during broker shutdown on bootstrap failure

s3stream/src/test/java/com/automq/stream/s3/S3StorageTest.java
Added comprehensive unit tests for the WALCallbackSequencer class to improve code coverage and test edge cases. The new tests focus on:
- Testing `after()` method behavior when a stream queue becomes empty
- Testing `tryFree()` method with both empty and non-empty queues
- Testing exception handling in the `before()` method
- Testing `after()` method with requests having different offsets than expected
- Added 5 new test methods to S3StorageTest.java to cover different edge cases
- Ensured tests verify behavior through public APIs since some fields are private
- Verified correct sequencing behavior for WAL callbacks, particularly in edge cases
=> fix(s3stream): Add unit tests for WALCallbackSequencer (#2368)

s3stream/src/test/java/com/automq/stream/s3/operator/TrafficRegulatorTest.java
This PR adds comprehensive unit tests for the TrafficRegulator class to validate its dynamic rate adjustment logic.
Test scenarios were added:
- Rate decrease logic
- Rate increase logic
- Success rate history handling
closes #2366
=> fix(s3stream): Add unit tests for TrafficRegulator (#2366)

CONTRIBUTING_GUIDE.md
In the JDK virtual machine parameters, `-Xms` is greater than `-Xmx`, which will generate an error of `Initial heap size set to a larger value than the maximum heap size`.
=> docs: Update IDE launch configuration in contribution guide

s3stream/src/main/java/com/automq/stream/s3/operator/AwsObjectStorage.java
=> fix(s3stream): Set default aws provider as fallback provider

s3stream/src/main/java/com/automq/stream/s3/index/LocalStreamRangeIndexCache.java, s3stream/src/test/java/com/automq/stream/s3/index/LocalStreamRangeIndexCacheTest.java
the range index of local stream may be espaped from compaction when all streams in a stream set object are deleted at once thus lead to memory leak
=> fix(s3stream): fix potential index leak on stream deletion

CONTRIBUTING_GUIDE.md, s3stream/src/main/java/com/automq/stream/s3/S3Storage.java, s3stream/src/main/java/com/automq/stream/s3/compact/CompactionManager.java, s3stream/src/main/java/com/automq/stream/s3/operator/AbstractObjectStorage.java, s3stream/src/main/java/com/automq/stream/s3/wal/benchmark/WriteBench.java, s3stream/src/main/java/com/automq/stream/s3/wal/impl/block/SlidingWindowService.java, s3stream/src/test/java/com/automq/stream/s3/operator/TrafficRateLimiterTest.java, s3stream/src/test/java/com/automq/stream/s3/wal/util/WALBlockDeviceChannelTest.java
Issue: #2358
This is my first attempt at modification, please point out if there are any mistakes and I will continue to correct them.
(There may be some missing parts. ?)
=> perf: Standardize ExecutorService Shutdown with Safety Wrapper.

.github/workflows/build.yml
Just as the other "trial" commit I have thinking of ways to re-factor the _Github Actions_ build process.
This is just a minor add-on but I think it would be an important one to include.
- [x ] Verify design and implementation 
- [ x] Verify test coverage and CI build status
- [ x] Verify documentation (including upgrade notes)
=> chore: trigger build when the status of PR is ready_for_review

CONTRIBUTING_GUIDE.md
Updated CONTRIBUTING_GUIDE.md to clarify the use of YAML issue templates when creating new issues. This ensures the contribution guide accurately reflects the current process for submitting issues via the forms in the `.github/ISSUE_TEMPLATE` directory.
Closes #2483
This is a documentation-only change. I have manually verified that the updated instructions in `CONTRIBUTING_GUIDE.md` are clear and the link to create a new issue works correctly.
=> docs: Update contributing guide regarding issue templates

automq-shell/src/main/java/com/automq/shell/AutoMQApplication.java
Remove unnecessary `else` block (**shell/AutoMQApplication.java**).
The `if` block is already returning.
This isn't a feature/bug fix. The code have no
crucial changes.
=> refactor(early returning): remove unnecessary conditional block

tools/src/main/java/org/apache/kafka/tools/automq/PerfCommand.java, tools/src/main/java/org/apache/kafka/tools/automq/perf/PerfConfig.java, tools/src/main/java/org/apache/kafka/tools/automq/perf/TopicService.java
feat: Add --catchup-topic-prefix for performance testing
Fixes #2373
**Detailed Description:**
This change introduces a new feature to the `automq-perf-test.sh` script to facilitate "catch-up read" (cold read) performance testing by reusing existing topics. This is particularly useful for scenarios where the message accumulation phase is time-consuming and needs to be bypassed for repeated cold read tests.
Two new command-line arguments have been added to `PerfConfig.java` and are accessible via `automq-perf-test.sh`:
*   `--catchup-topic-prefix <String>`: If specified, the performance test tool will search for existing topics that match this prefix (e.g., `common_topic_prefix_value + your_prefix`). If found, these topics will be used for the consumer/read phase of the test.
* …
=> feat: Add --catchup-topic-prefix for performance testing and solve the issue 

s3stream/src/main/java/com/automq/stream/s3/wal/impl/object/ObjectWALService.java, s3stream/src/main/java/com/automq/stream/s3/wal/impl/object/RecordAccumulator.java, s3stream/src/main/java/com/automq/stream/s3/wal/impl/object/WALObjectHeader.java, s3stream/src/test/java/com/automq/stream/s3/wal/impl/object/MockObjectStorage.java, s3stream/src/test/java/com/automq/stream/s3/wal/impl/object/ObjectWALServiceTest.java, s3stream/src/test/java/com/automq/stream/s3/wal/impl/object/RecordAccumulatorTest.java, s3stream/src/test/java/com/automq/stream/s3/wal/impl/object/WALObjectHeaderTest.java
resolve #2432
- Before
```
2025-04-18 07:42:14 - INFO Summary | Prod rate   1600.46 msg/s /  79.71 MiB/s | Prod total   0.48 M msg /  23.36 GiB /   0.00 K err | Cons rate   1600.44 msg/s /  79.71 MiB/s | Cons total   0.48 M msg /  23.36 GiB | Prod Latency (ms) avg:   267.319 - 50%:   233.070 - 75%:   276.479 - 90%:   416.589 - 95%:   545.547 - 99%:   759.195 - 99.9%:   972.191 - 99.99%:  1230.271 - Max:  1250.511 | E2E Latency (ms) avg:   272.780 - 50%:   237.312 - 75%:   280.909 - 90%:   436.249 - 95%:   547.739 - 99%:   778.615 - 99.9%:   981.371 - 99.99%:  1238.991 - Max:  1381.615
```
- After
```
2025-04-18 08:11:08 - INFO Summary | Prod rate   1601.42 msg/s /  79.76 MiB/s | Prod total   0.48 M msg /  23.40 GiB /   0.00 K err | Cons rate   1600.99 msg/s /  79.74 MiB/s | Cons total …
```
=> refactor(s3stream/object-wal): complete appends sequentially

.github/workflows/docker-bitnami-release.yaml, bin/automq-perf-test.sh, tools/src/main/java/org/apache/kafka/tools/automq/PerfCommand.java, tools/src/main/java/org/apache/kafka/tools/automq/perf/ConsumerService.java, tools/src/main/java/org/apache/kafka/tools/automq/perf/PerfConfig.java
This PR implements a new command-line parameter `--consumers-during-catchup` that allows users to control what percentage of consumer groups are activated during catch-up reads in performance testing.
This implementation adds:
A new `--consumers-during-catchup` parameter (0-100, default: 100%) to control the percentage of consumers activated during catch-up reads
Added the new parameter to (PerfConfig) class with proper validation
Enhanced (ConsumerService) with percentage-based consumer selection logic
Modified (PerfCommand) to utilize the new parameter during catch-up reads
Added documentation in the [automq-perf-test.sh] script
Resolves #2372
=> feat: Added consumer percentage control for catch-up reading in perf test

s3stream/src/main/java/com/automq/stream/s3/S3Storage.java, s3stream/src/main/java/com/automq/stream/utils/ExceptionUtil.java
This is a fully equivalent reconstruction.
=> refactor(s3stream): in preparation for segmented recovery

streams/src/test/java/org/apache/kafka/streams/tests/RelationalSmokeTest.java, tests/kafkatest/automq/compaction_test.py, tests/kafkatest/automq/memory_occupancy_test.py, tests/kafkatest/automq/quota_test.py, tests/kafkatest/automq/s3_leakage_test.py, tests/kafkatest/benchmarks/core/benchmark_test.py, tests/kafkatest/sanity_checks/test_performance_services.py, tests/kafkatest/services/log_compaction_tester.py, tests/kafkatest/tests/connect/connect_distributed_test.py, tests/kafkatest/tests/core/group_mode_transactions_test.py, tests/kafkatest/tests/core/reassign_partitions_test.py, tests/kafkatest/tests/core/replica_scale_test.py, tests/kafkatest/tests/core/round_trip_fault_test.py, tests/kafkatest/tests/core/snapshot_test.py, tests/kafkatest/tests/core/transactions_test.py, tests/kafkatest/tests/produce_consume_validate.py, tests/kafkatest/tests/streams/base_streams_test.py, tests/kafkatest/tests/streams/streams_broker_down_resilience_test.py, tests/kafkatest/tests/streams/streams_relational_smoke_test.py, tests/kafkatest/tests/streams/streams_standby_replica_test.py
=> fix(e2e): cherry pick fix e2e 1.5

core/src/main/scala/kafka/log/stream/s3/metadata/StreamMetadataManager.java, metadata/src/main/java/org/apache/kafka/image/S3StreamsMetadataImage.java
Issue: When getting data from a non-thread-safe HashMap while a put operation is occurring simultaneously, it is possible that due to the resize of the HashMap, the actually existing data cannot be retrieved.
=> fix(image): guard streams image access with lock to prevent data loss

core/src/main/scala/kafka/log/stream/s3/metadata/StreamMetadataManager.java, metadata/src/main/java/org/apache/kafka/image/S3StreamsMetadataImage.java
cherry-pick https://github.com/AutoMQ/automq/pull/2653
=> fix(image): guard streams image access with lock to prevent data loss(#2653)

core/src/main/scala/kafka/log/streamaspect/ClientWrapper.java
Improve `ClientWrapper` resource release to prevent resource leakage.
=> fix(s3stream): improve ClientWrapper resource release to prevent resource leakage

s3stream/src/main/java/com/automq/stream/s3/operator/AwsObjectStorage.java
This commit fixes an issue where the doList method in AwsObjectStorage.java did not handle paginated results from the S3 listObjectsV2 API. The method now recursively fetches all pages of objects, ensuring that it can retrieve more than the default 1000 objects.
=> fix: support list more than 1000 objects by prefix (#2660)

core/src/main/java/kafka/automq/table/CredentialProviderHolder.java
Refactors CredentialProviderHolder to prevent "Connection Pool Shutdown" errors by creating a new provider instance upon each invocation of create().
Previously, a single static `AwsCredentialsProvider` was shared globally. If this provider was closed, it would affect all subsequent operations. By creating a new provider on each `create()` call from Iceberg, this change removes the global singleton and isolates provider instances.
Fixes #2680
https://github.com/apache/iceberg/pull/8677
> **How do I fix "java.lang.IllegalStateException: Connection pool shut down" error?**
> 
> You attempted to use the credentials provider returned from DefaultCredentialsProvider#create() after it was closed. [DefaultCredentialsProvider#create](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk …
=> feat(catalog): avoid static global credentials provider

core/src/main/scala/kafka/log/LogCleaner.scala, core/src/main/scala/kafka/log/streamaspect/ElasticLogSegment.java, core/src/test/scala/unit/kafka/log/LogCleanerTest.scala, s3stream/src/main/java/com/automq/stream/s3/S3Stream.java
This commit addresses an issue where a log segment could accommodate more than Integer.MAX_VALUE records, leading to a potential integer overflow when calculating relative offsets.
The root cause was that the check `offset - baseOffset <= Integer.MAX_VALUE` allowed a relative offset to be exactly `Integer.MAX_VALUE`. Since offsets are 0-based, this allows for `Integer.MAX_VALUE + 1` records, which cannot be represented by a standard Integer.
This fix implements the following changes:
1.  In `ElasticLogSegment`, the offset validation is changed from `<=` to `< Integer.MAX_VALUE` to ensure the relative offset strictly fits within an Integer's bounds.
2.  In `LogCleaner`, a new segment grouping method `groupSegmentsBySizeV2` is introduced for `ElasticUnifiedLog`. This method uses the same …
=> fix(log): Prevent potential offset overflow in ElasticLogSegment

core/src/main/scala/kafka/log/LogCleaner.scala, core/src/main/scala/kafka/log/streamaspect/ElasticLogSegment.java, core/src/test/scala/unit/kafka/log/LogCleanerTest.scala, s3stream/src/main/java/com/automq/stream/s3/S3Stream.java
cherry-pick 201c6eb8320f07e50e19c4a1d5b1a2d319cc8b0d
* fix(log): Prevent potential offset overflow in ElasticLogSegment
This commit addresses an issue where a log segment could accommodate more than Integer.MAX_VALUE records, leading to a potential integer overflow when calculating relative offsets.
The root cause was that the check `offset - baseOffset <= Integer.MAX_VALUE` allowed a relative offset to be exactly `Integer.MAX_VALUE`. Since offsets are 0-based, this allows for `Integer.MAX_VALUE + 1` records, which cannot be represented by a standard Integer.
This fix implements the following changes:
1.  In `ElasticLogSegment`, the offset validation is changed from `<=` to `< Integer.MAX_VALUE` to ensure the relative offset strictly fits within an Integer's bounds.
2.  In `LogCleaner`, a …
=> fix(log): Prevent potential offset overflow in ElasticLogSegment (#2720)

s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/StreamReader.java, s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/StreamReaders.java, s3stream/src/test/java/com/automq/stream/s3/cache/blockcache/StreamReadersTest.java
fix https://github.com/AutoMQ/automq/issues/2716
=> fix(streamReader): implement scheduled cleanup for expired stream readers

s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/StreamReader.java, s3stream/src/main/java/com/automq/stream/s3/cache/blockcache/StreamReaders.java, s3stream/src/test/java/com/automq/stream/s3/cache/blockcache/StreamReadersTest.java
cherry-pick https://github.com/AutoMQ/automq/commit/59a92fa6a894d961d144a71dd58c2ebfe47c34e4
fix: https://github.com/AutoMQ/automq/issues/2716
* refactor(StreamReader, StreamReaders): inject Time for testable time control and remove reflection from tests
- Add Time dependency to StreamReader and StreamReaders for time-related operations
- Update constructors to accept Time, defaulting to Time.SYSTEM
- Replace System.currentTimeMillis() with time.milliseconds() throughout
- Refactor StreamReadersTest to use MockTime for simulating time passage
- Remove reflection-based time manipulation in tests for cleaner and safer testing
=> fix(streamReader): implement scheduled cleanup for expired stream readers (#2719)

core/src/main/scala/kafka/server/streamaspect/ElasticReplicaManager.scala, s3stream/src/main/java/com/automq/stream/s3/S3Stream.java
Consider the following scenario:
1. A Fetch request contains partitions P1 and P2. The data of P1 is in LogCache, while the data of P2 is not.
2. First, a fast read will be attempted. At this time, P1 will return data and consume Network Out, and P2 will return a FastReadException.
3. Due to the FastReadException, the entire Fetch attempts a slow read. At this time, both P1 and P2 return data and consume Network Out.
4. At this point, the Network Out in step 2 is consumed repeatedly.
Solution: Move the S3Stream network out consumption to ElasticReplicaManager. Avoid the network out traffic over-consumed, when there are mixin(tail read & catch-up read) partitions reading.
=> fix(s3stream): fix the network out over-consumed

core/src/main/java/kafka/automq/table/binder/AbstractTypeAdapter.java, core/src/main/java/kafka/automq/table/binder/AvroValueAdapter.java, core/src/main/java/kafka/automq/table/binder/RecordBinder.java, core/src/main/java/kafka/automq/table/binder/TypeAdapter.java, core/src/test/java/kafka/automq/table/binder/AvroRecordBinderTest.java, core/src/test/java/kafka/automq/table/binder/PerformanceComparisonTest.java, core/src/test/java/kafka/automq/table/binder/PerformanceProfilingTest.java
https://github.com/AutoMQ/automq/issues/2743
=> feat(binder): implement AvroValueAdapter and RecordBinder for Avro to Iceberg conversion

core/src/main/java/kafka/automq/table/deserializer/proto/HeaderBasedSchemaResolutionResolver.java, core/src/main/java/kafka/automq/table/process/Converter.java, core/src/main/java/kafka/automq/table/process/DataError.java, core/src/main/java/kafka/automq/table/process/DefaultRecordProcessor.java, core/src/main/java/kafka/automq/table/process/convert/AvroRegistryConverter.java, core/src/main/java/kafka/automq/table/process/convert/RawConverter.java, core/src/main/java/kafka/automq/table/process/convert/RegistrySchemaConverter.java, core/src/main/java/kafka/automq/table/process/exception/InvalidDataException.java, core/src/main/java/kafka/automq/table/transformer/ProtoToAvroConverter.java, core/src/main/java/kafka/automq/table/transformer/RegistrySchemaAvroConverter.java, core/src/main/java/kafka/automq/table/worker/IcebergWriter.java, core/src/test/java/kafka/automq/table/worker/MemoryWriter.java
1. `DATA_ERROR`:  Indicates that the record's data is malformed or invalid.This can be due to a null payload, incorrect data size, or a missing or unknown magic byte that prevents further processing.
2. `CONVERT_ERROR`: Indicates a failure during the data deserialization or conversion step.This can be caused by an inability to fetch a schema from a registry, serialization errors (e.g., Avro, Protobuf), or other schema-related failures.
3. `TRANSFORMATION_ERROR`: Indicates a failure within a data transformation step.This can be due to the input data not matching the format expected by a transform (e.g., an invalid Debezium record).
4. `UNKNOW_ERROR`:  Unknown exception during processing.
=> refactor(process): Improve and clarify data processing error handling

s3stream/src/main/java/com/automq/stream/s3/wal/util/AbstractWALChannel.java
=> feat(nfs-wal): initial implementation of nfs wal

.github/workflows/docker-kafka-release.yaml, docker/automq-feat-kafka-docker.patch, docker/jvm/Dockerfile, docker/jvm/launch
- Adapted Kafka Docker image build process for improved compatibility with main branch
- Optimized build scripts and dependency management to simplify image creation
- Fixed environment variable and configuration compatibility issues within containers
- Added/updated related documentation and usage examples
- Kafka Docker image build workflow and related scripts
- Docker deployment documentation
- Dependency configuration and environment adaptation
Please pay special attention to changes in Dockerfile, build scripts, and related configurations to ensure image usability across different environments.
=> feat(docker): kafka docker image adapt

server-common/src/main/java/org/apache/kafka/server/common/automq/TableTopicConfigValidator.java, server-common/src/test/java/org/apache/kafka/server/common/automq/TableTopicConfigValidatorTest.java
- The error indicates the configuration value `month(ts)` is invalid because it is not recognized as a valid list string.
```
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.InvalidConfigurationException: Invalid value month(ts) for configuration : Invalid list string month(ts)
at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:180)
at kafka.admin.ConfigCommand$.alterConfig(ConfigCommand.scala:382)
at kafka.admin.ConfigCommand$.processCommand(ConfigCommand.scala:349)
at kafka.admin.ConfigCommand$.main(ConfigCommand.scala:98)
at …
```
=> fix(config): remove exception for invalid list string in TableTopicConfigValidator

core/src/main/java/kafka/automq/zerozone/SnapshotReadPartitionsManager.java, core/src/main/java/kafka/automq/zerozone/SubscriberRequester.java
Bug: when the SubscriberRequester#reset happens between request and response. The response will override the sessionId and sessionEpoch again. Then the reset isn't working.
=> fix(zerozone2): fix reset bug cause skip

core/src/main/java/kafka/automq/zerozone/SnapshotReadPartitionsManager.java, core/src/main/java/kafka/automq/zerozone/SnapshotWithOperation.java, core/src/main/java/kafka/automq/zerozone/SubscriberRequester.java, core/src/main/java/kafka/automq/zerozone/ZeroZoneTrafficInterceptor.java, core/src/main/scala/kafka/server/streamaspect/ElasticKafkaApis.scala, core/src/test/java/kafka/automq/zerozone/SnapshotReadPartitionsManagerTest.java
The expired offsetForLeaderEpoch in snapshot-read partition may cause the consumer offset truncation.
=> fix(zerozone2): fix the expired offsetForLeaderEpoch

core/src/main/java/kafka/automq/zerozone/SnapshotReadPartitionsManager.java
cherry-pick https://github.com/AutoMQ/automq/pull/2894
=> fix(zerozone2): gracefully await subscriber close

core/src/main/scala/kafka/network/SocketServer.scala, core/src/main/scala/kafka/server/ReplicaManager.scala, core/src/main/scala/kafka/server/streamaspect/ElasticReplicaManager.scala, server/src/main/java/org/apache/kafka/network/SocketServerConfigs.java
cherry-pick https://github.com/AutoMQ/automq/pull/2903
=> fix(issue2902): change Verification.waitingRequests to unbounded queue to fix the deadlock

core/src/main/java/kafka/automq/partition/snapshot/PartitionSnapshotsManager.java, core/src/main/scala/kafka/cluster/Partition.scala
When there isn't any new record and the partition is reassigned, the snapshot-read partition only applies the leader epoch that trigger the partition reassignment (not the final leader epoch). This will cause OFFSET_FOR_LEADER_EPOCH request return UNKNOWN_LEADER_EPOCH.
=> fix(zerozone2): fix epoch missing update when there isn't new record
